const createBox = (title, ...schema) => ({ title, schema })
const createTitleBox = (title, subtitle, ...schema) => ({ title, subtitle, schema })
const createSimpleBox = (...schema) => ({ title: undefined, schema })
const createJSONBox = (title, key, rows = 10) => createBox(title, { type: "json", rows, key })
const createArrayBox = (title, key) => createBox(title, { type: "array", key })

const PROTECTED_HINT = "危险操作，禁止修改，如需请修改配置文件"

const PLUGIN_PROP_ENABLE = { label: "启用", type: "switch", key: "ENABLE" }
const PLUGIN_PROP_NAME = { label: "名称", type: "text", key: "NAME", placeholder: "为空则使用默认名" }
const PLUGIN_PROP_HOTKEY = { label: "快捷键", type: "hotkey", key: "HOTKEY" }

const PLUGIN_PROP_ENABLE_PROTECTED = { label: "启用", type: "switch", key: "ENABLE", tooltip: PROTECTED_HINT, disabled: true }

const CUSTOM_PLUGIN_PROP_ENABLE = { label: "启用", type: "switch", key: "enable" }
const CUSTOM_PLUGIN_PROP_NAME = { label: "名称", type: "text", key: "name", placeholder: "为空则使用默认名" }
const CUSTOM_PLUGIN_PROP_HIDE = { label: "隐藏", type: "switch", key: "hide" }
const CUSTOM_PLUGIN_BASE_ORDER = { label: "排序", type: "number", key: "order" }
const CUSTOM_PLUGIN_BASE_HOTKEY = { label: "快捷键", type: "hotkey", key: "hotkey" }

const PLUGIN_BASE_PROP_LITE_SCHEMA = createSimpleBox(PLUGIN_PROP_ENABLE, PLUGIN_PROP_NAME)
const PLUGIN_BASE_PROP_FULL_SCHEMA = createSimpleBox(PLUGIN_PROP_ENABLE, PLUGIN_PROP_NAME, PLUGIN_PROP_HOTKEY)
const PLUGIN_BASE_PROP_PROTECT_LITE_SCHEMA = createSimpleBox(PLUGIN_PROP_ENABLE_PROTECTED, PLUGIN_PROP_NAME)
const PLUGIN_BASE_PROP_PROTECT_FULL_SCHEMA = createSimpleBox(PLUGIN_PROP_ENABLE_PROTECTED, PLUGIN_PROP_NAME, PLUGIN_PROP_HOTKEY)

const CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA = createSimpleBox(CUSTOM_PLUGIN_PROP_ENABLE, CUSTOM_PLUGIN_PROP_HIDE, CUSTOM_PLUGIN_PROP_NAME, CUSTOM_PLUGIN_BASE_ORDER)
const CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA = createSimpleBox(CUSTOM_PLUGIN_PROP_ENABLE, CUSTOM_PLUGIN_PROP_HIDE, CUSTOM_PLUGIN_PROP_NAME, CUSTOM_PLUGIN_BASE_ORDER, CUSTOM_PLUGIN_BASE_HOTKEY)

const TEMPLATE_SCHEMA = createBox("模板", { type: "textarea", rows: 10, key: "TEMPLATE" })
const RESTORE_PLUGIN_SCHEMA = createSimpleBox({ label: "恢复默认", type: "action", action: "restoreSettings" })

const CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS = {
    close: "关闭",
    download: "下载",
    scroll: "定位到文档",
    play: "轮播",
    location: "打开图片路径",
    nextImage: "下一张图",
    previousImage: "上一张图",
    firstImage: "第一张图",
    lastImage: "最后一张图",
    thumbnailNav: "显示/隐藏缩略图列表",
    waterFall: "显示/隐藏瀑布流",
    zoomIn: "放大图片",
    zoomOut: "缩小图片",
    rotateLeft: "向左旋转",
    rotateRight: "向右旋转",
    hFlip: "水平翻转",
    vFlip: "垂直翻转",
    translateLeft: "向左移动",
    translateRight: "向右移动",
    translateUp: "向上移动",
    translateDown: "向下移动",
    incHSkew: "增大水平倾斜",
    decHSkew: "减小水平倾斜",
    incVSkew: "增大垂直倾斜",
    decVSkew: "减小垂直倾斜",
    originSize: "还原尺寸",
    fixScreen: "适配屏幕",
    autoSize: "调整图片大小",
    restore: "还原",
    info: "功能提示",
    dummy: "无功能",
}

const SETTING_SCHEMAS = {
    global: [
        createSimpleBox(
            { label: "总开关", type: "switch", key: "ENABLE", tooltip: PROTECTED_HINT, disabled: true },
            { label: "语言", type: "select", key: "LOCALE", options: { "auto": "AUTO", "en": "English", "zh-CN": "简体中文", "zh-TW": "繁體中文" } },
            {
                label: "图表退出交互模式方式",
                type: "select",
                key: "EXIT_INTERACTIVE_MODE",
                minItems: 1,
                options: { click_exit_button: "点击按钮", ctrl_click_fence: "Ctrl+Click" }
            }
        ),
        createSimpleBox(
            { label: "配置目录", type: "action", action: "openSettingsFolder" },
            { label: "备份配置", type: "action", action: "backupSettings" },
            { label: "恢复默认", type: "action", action: "restoreSettings" },
            { label: "恢复所有默认", type: "action", action: "restoreAllSettings" },
        ),
        createSimpleBox(
            { label: "GitHub", type: "action", action: "visitRepo" },
            { label: "Version", key: "__version__", type: "static" },
        )
    ],
    window_tab: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "标签外观",
            { label: "关闭按钮", type: "switch", key: "SHOW_TAB_CLOSE_BUTTON" },
            { label: "文件扩展名", type: "switch", key: "TRIM_FILE_EXT" },
            { label: "同名文件显示目录名", type: "switch", key: "SHOW_DIR_ON_DUPLICATE" },
            { label: "隐藏标题栏", type: "switch", tooltip: "开启一体化窗口选项后，隐藏标题栏", key: "HIDE_WINDOW_TITLE_BAR" },
            { label: "最小宽度", type: "text", tooltip: "不可超过 400px", key: "TAB_MIN_WIDTH" },
            { label: "最大宽度", type: "text", tooltip: "不可超过 400px", key: "TAB_MAX_WIDTH" },
            { label: "最大数量", type: "number", tooltip: "-1 表示无限制", key: "MAX_TAB_NUM" },
            {
                label: "右键菜单选项",
                type: "select",
                key: "CONTEXT_MENU",
                options: {
                    closeTab: "关闭标签",
                    closeOtherTabs: "关闭其他标签",
                    closeLeftTabs: "关闭左侧所有标签",
                    closeRightTabs: "关闭右侧所有标签",
                    copyPath: "复制当前文件路径",
                    showInFinder: "在文件资源管理器中打开",
                    openInNewWindow: "在新窗口中打开",
                    sortTabs: "排序标签",
                }
            }
        ),
        createBox(
            "标签行为",
            { label: "新建标签位置", type: "select", key: "NEW_TAB_POSITION", options: { right: "当前标签右侧", end: "标签栏最右侧" } },
            { label: "关闭标签后", type: "select", key: "TAB_SWITCH_ON_CLOSE", options: { left: "激活左侧标签", right: "激活右侧标签", latest: "激活最近浏览标签" } },
            { label: "关闭最后的标签后", type: "select", key: "LAST_TAB_CLOSE_ACTION", options: { blankPage: "显示空白页", reconfirm: "弹出确认对话框", exit: "退出" } },
        ),
        createArrayBox("快捷键：关闭标签", "CLOSE_HOTKEY"),
        createArrayBox("快捷键：上一个标签", "SWITCH_PREVIOUS_TAB_HOTKEY"),
        createArrayBox("快捷键：下一个标签", "SWITCH_NEXT_TAB_HOTKEY"),
        createArrayBox("快捷键：排序标签", "SORT_TABS_HOTKEY"),
        createArrayBox("快捷键：复制当前文件路径", "COPY_PATH_HOTKEY"),
        createArrayBox("快捷键：临时显示/隐藏标签栏", "TOGGLE_TAB_BAR_HOTKEY"),
        createBox(
            "鼠标交互",
            { label: "Ctrl+Click 新窗口打开", type: "switch", key: "CTRL_CLICK_TO_NEW_WINDOW" },
            { label: "Ctrl+Wheel 切换标签", type: "switch", key: "CTRL_WHEEL_TO_SWITCH" },
            { label: "中键关闭标签", type: "switch", key: "MIDDLE_CLICK_TO_CLOSE" },
            { label: "鼠标悬停显示文件路径", type: "switch", key: "SHOW_FULL_PATH_WHEN_HOVER" },
            { label: "JetBrains 风格的拖拽方式", type: "switch", key: "JETBRAINS_DRAG_STYLE" },
            { label: "禁止垂直拖拽", type: "switch", key: "LOCK_DRAG_Y_AXIS" },
            { label: "限制竖直拖拽", type: "switch", key: "LIMIT_TAB_Y_AXIS_WHEN_DRAG" },
            { label: "限制竖直拖拽幅度", type: "number", explain: "拖拽垂直距离少于 X 倍标签高度，视为无垂直移动", min: 0.1, max: 3, step: 0.1, key: "Y_AXIS_LIMIT_THRESHOLD" },
            { label: "拖拽以新建窗口", type: "number", key: "DRAG_NEW_WINDOW_THRESHOLD", explain: "拖拽垂直距离超过 X 倍标签高度，视为新建窗口", tooltip: "-1 表示不启用" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    search_multi: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "搜索结果",
            { label: "使用相对路径", type: "switch", key: "RELATIVE_PATH" },
            { label: "显示文件扩展名", type: "switch", key: "SHOW_EXT" },
            { label: "显示文件最后修改时间", type: "switch", key: "SHOW_MTIME" },
            { label: "隐藏按钮提示", type: "switch", key: "REMOVE_BUTTON_HINT" },
            { label: "高亮最大数量", type: "number", key: "MAX_HITS" },
        ),
        createBox(
            "搜索",
            { label: "区分大小写", type: "switch", key: "CASE_SENSITIVE" },
            { label: "搜索优化", type: "switch", explain: "副作用：影响高亮块顺序", key: "OPTIMIZE_SEARCH" },
            { label: "允许最大文件", type: "number", key: "MAX_SIZE", unit: "字节" },
        ),
        createBox(
            "窗口交互",
            { label: "输入框为空且失去焦点时，隐藏窗口", type: "switch", key: "AUTO_HIDE" },
            { label: "输入框为空且键入退格键时，隐藏窗口", type: "switch", key: "BACKSPACE_TO_HIDE" },
            { label: "Ctrl+鼠标拖拽输入框以移动窗口", type: "switch", key: "ALLOW_DRAG" },
        ),
        createArrayBox("允许文件扩展名", "ALLOW_EXT"),
        createArrayBox("忽略搜索的文件夹", "IGNORE_FOLDERS"),
        createArrayBox("高亮颜色列表", "HIGHLIGHT_COLORS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    commander: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "命令显示方式",
            {
                label: "通过快捷方式执行命令时",
                type: "select",
                key: "QUICK_RUN_DISPLAY",
                options: { echo: "立即弹窗并回显输出", always: "执行结束后弹窗并显示输出", error: "仅在错误时弹窗并显示输出", silent: "静默执行，不显示任何输出" }
            },
            {
                label: "通过命令框执行命令时",
                type: "select",
                key: "COMMIT_RUN_DISPLAY",
                options: { echo: "立即回显输出", always: "执行结束后显示输出" }
            },
        ),
        createBox(
            "窗口交互",
            { label: "输入框为空且键入退格键时，隐藏窗口", type: "switch", key: "BACKSPACE_TO_HIDE" },
            { label: "Ctrl+鼠标拖拽输入框以移动窗口", type: "switch", key: "ALLOW_DRAG" },
        ),
        createJSONBox("预设的常用命令列表", "BUILTIN"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    md_padding: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createArrayBox("忽略词组", "IGNORE_WORDS"),
        createArrayBox("忽略正则表达式", "IGNORE_PATTERNS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    read_only: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "只读状态",
            { label: "默认开启", type: "switch", key: "READ_ONLY_DEFAULT" },
            { label: "单击图片和行内公式不会自动展开", type: "switch", key: "NO_EXPAND_WHEN_READ_ONLY" },
            { label: "展开的图片和行内公式自动收缩", type: "switch", key: "REMOVE_EXPAND_WHEN_READ_ONLY" },
            { label: "单击超链接即可跳转", type: "switch", key: "CLICK_HYPERLINK_TO_OPEN_WHEN_READ_ONLY" },
            { label: "禁用部分右键菜单选项", type: "switch", key: "DISABLE_CONTEXT_MENU_WHEN_READ_ONLY" },
            { label: "提示文字", type: "text", key: "SHOW_TEXT" },
        ),
        createArrayBox("只读状态下保持可用的右键菜单选项", "REMAIN_AVAILABLE_MENU_KEY"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    blur: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox(
            { label: "默认开启", type: "switch", key: "BLUR_DEFAULT" },
            { label: "鼠标悬停恢复可见", type: "switch", key: "RESRTORE_WHEN_HOVER" },
            { label: "模糊类型", type: "select", key: "BLUR_TYPE", options: { blur: "模糊", hide: "隐藏" } },
            { label: "模糊等级", type: "number", key: "BLUR_LEVEL", unit: "像素" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    dark: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox({ label: "默认开启", type: "switch", key: "DARK_DEFAULT" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    no_image: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox(
            { label: "默认开启", type: "switch", key: "DEFAULT_NO_IMAGE_MODE" },
            { label: "鼠标悬停恢复可见", type: "switch", key: "RESHOW_WHEN_HOVER" },
            { label: "动画持续时间", type: "number", key: "TRANSITION_DURATION", unit: "毫秒" },
            { label: "动画延迟时间", type: "number", key: "TRANSITION_DELAY", unit: "毫秒" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    toolbar: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "搜索栏位置",
            { label: "垂直定位", type: "range", min: 0, max: 100, step: 1, key: "TOOLBAR_TOP_PERCENT" },
            { label: "宽度", type: "range", min: 0, max: 100, step: 1, key: "TOOLBAR_WIDTH_PERCENT" },
        ),
        createBox(
            "窗口交互",
            { label: "输入框为空且失去焦点时，隐藏窗口", type: "switch", key: "AUTO_HIDE" },
            { label: "输入框为空且键入退格键时，隐藏窗口", type: "switch", key: "BACKSPACE_TO_HIDE" },
        ),
        createBox(
            "输入",
            {
                label: "默认搜索工具",
                type: "select",
                key: "DEFAULT_TOOL",
                options: { "": "无", plu: "插件", tab: "标签", his: "最近文件", ops: "常用操作", mode: "文件模式", theme: "主题", out: "文档大纲", func: "功能列表", all: "混合查找" }
            },
            { label: "启用负向查询", type: "switch", key: "USE_NEGATIVE_SEARCH" },
            { label: "输入法优化", type: "switch", explain: "等待输入法输入完毕再执行搜索，减少无效搜索", key: "PAUSE_ON_COMPOSITION" },
            { label: "输入防抖", type: "number", key: "DEBOUNCE_INTERVAL", unit: "毫秒" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    resize_image: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "图片",
            { label: "记忆放缩状态", type: "switch", key: "RECORD_RESIZE" },
            { label: "允许超出边界", type: "switch", key: "ALLOW_EXCEED_LIMIT" },
            { label: "对齐方式", type: "select", key: "IMAGE_ALIGN", options: { center: "居中对齐", left: "左对齐", right: "右对齐" } },
        ),
        createBox(
            "鼠标滚轮的修饰键",
            { label: "临时修改图片大小", explain: "举例：填入 alt，则 Alt+Wheel 临时调整图片大小", type: "text", key: "MODIFIER_KEY.TEMPORARY" },
            { label: "永久修改图片大小（转为 HTML 语法）", explain: "举例：填入 alt，则 Alt+Wheel 永久修改图片大小", type: "text", key: "MODIFIER_KEY.PERSISTENT" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    resize_table: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "表格",
            { label: "记忆放缩状态", type: "switch", key: "RECORD_RESIZE" },
            { label: "移除单元格最小宽度限制", type: "switch", key: "REMOVE_MIN_CELL_WIDTH" },
            { label: "可拖拽识别范围", type: "number", key: "DRAG_THRESHOLD", unit: "像素" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    datatables: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "增强表格",
            { label: "启用排序", type: "switch", key: "ORDERING" },
            { label: "默认排序", type: "switch", key: "DEFAULT_ORDER" },
            { label: "启用搜索", type: "switch", key: "SEARCHING" },
            { label: "启用正则表达式搜索", type: "switch", key: "REGEX" },
            { label: "搜索区分大小写", type: "switch", key: "CASE_INSENSITIVE" },
            { label: "允许表格减少高度", type: "switch", key: "SCROLL_COLLAPSE" },
            { label: "启用分页", type: "switch", key: "PAGING" },
            { label: "单页数据量", type: "number", key: "PAGE_LENGTH", unit: "条" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    go_top: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "快捷键",
            { label: "至顶", type: "hotkey", key: "HOTKEY_GO_TOP" },
            { label: "至底", type: "hotkey", key: "HOTKEY_GO_BOTTOM" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    markmap: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "思维导图",
            { label: "启用", type: "switch", key: "ENABLE_TOC_MARKMAP" },
            { label: "快捷键", type: "hotkey", key: "TOC_HOTKEY" },
            { label: "兼容跳级标题", type: "switch", key: "FIX_ERROR_LEVEL_HEADER" },
            { label: "大纲变化后自动更新", type: "switch", key: "AUTO_UPDATE" },
            { label: "调整窗口后自动适配", type: "switch", key: "AUTO_FIT_WHEN_RESIZE" },
            { label: "更新图形后自动适配", type: "switch", key: "AUTO_FIT_WHEN_UPDATE" },
            { label: "更新图形后保持节点折叠状态", type: "switch", key: "KEEP_FOLD_STATE_WHEN_UPDATE" },
            { label: "点击节点跳转到文档对应章节", type: "switch", key: "CLICK_TO_POSITIONING" },
            { label: "折叠节点后自动折叠章节内容", explain: "实验性特性，仅当「章节折叠」插件开启时可用", type: "switch", key: "AUTO_COLLAPSE_PARAGRAPH_WHEN_FOLD" },
            { label: "定位视口高度", type: "range", min: 0.1, max: 0.95, step: 0.01, key: "POSITIONING_VIEWPORT_HEIGHT" },
            { label: "初始窗口宽度", type: "range", min: 20, max: 95, step: 1, key: "WIDTH_PERCENT_WHEN_INIT" },
            { label: "初始窗口高度", type: "range", min: 20, max: 95, step: 1, key: "HEIGHT_PERCENT_WHEN_INIT" },
            { label: "固定顶部的窗口高度", type: "range", min: 20, max: 95, step: 1, key: "HEIGHT_PERCENT_WHEN_PIN_TOP" },
            { label: "固定右侧的窗口宽度", type: "range", min: 20, max: 95, step: 1, key: "WIDTH_PERCENT_WHEN_PIN_RIGHT" },
            { label: "鼠标悬停节点边框样式", type: "text", key: "NODE_BORDER_WHEN_HOVER" },
        ),
        createBox(
            "思维导图默认图形",
            { label: "允许缩放", type: "switch", key: "DEFAULT_TOC_OPTIONS.zoom" },
            { label: "允许平移", type: "switch", key: "DEFAULT_TOC_OPTIONS.pan" },
            { label: "折叠/展开节点后，图形自动适配窗口", type: "switch", key: "DEFAULT_TOC_OPTIONS.autoFit" },
            { label: "首次渲染分支展开等级", type: "range", min: 1, max: 6, step: 1, key: "DEFAULT_TOC_OPTIONS.initialExpandLevel" },
            { label: "固定颜色的分支等级", type: "range", min: 1, max: 6, step: 1, key: "DEFAULT_TOC_OPTIONS.colorFreezeLevel" },
            { label: "窗口填充率", type: "range", min: 0.5, max: 1, step: 0.01, key: "DEFAULT_TOC_OPTIONS.fitRatio" },
            { label: "节点最大长度", type: "number", tooltip: "0 表示无限制", min: 0, max: 1000, step: 10, key: "DEFAULT_TOC_OPTIONS.maxWidth", unit: "像素" },
            { label: "节点水平间距", type: "number", min: 0, max: 200, step: 1, key: "DEFAULT_TOC_OPTIONS.spacingHorizontal", unit: "像素" },
            { label: "节点垂直间距", type: "number", min: 0, max: 100, step: 1, key: "DEFAULT_TOC_OPTIONS.spacingVertical", unit: "像素" },
            { label: "节点内部边距", type: "number", min: 0, max: 100, step: 1, key: "DEFAULT_TOC_OPTIONS.paddingX", unit: "像素" },
            { label: "动画持续时间", type: "number", min: 0, max: 1000, step: 10, key: "DEFAULT_TOC_OPTIONS.duration", unit: "毫秒" },
        ),
        createArrayBox("思维导图默认配色方案", "DEFAULT_TOC_OPTIONS.color"),
        createJSONBox("思维导图的预设配色方案列表", "CANDIDATE_COLOR_SCHEMES"),
        createBox(
            "思维导图导出",
            { label: "保留透明通道", type: "switch", key: "DOWNLOAD_OPTIONS.KEEP_ALPHA_CHANNEL" },
            { label: "删除无用的类名", type: "switch", key: "DOWNLOAD_OPTIONS.REMOVE_USELESS_CLASSES" },
            { label: "移除 &lt;foreignObject&gt; 标签，并替换为 &lt;text&gt; 标签", type: "switch", key: "DOWNLOAD_OPTIONS.REMOVE_FOREIGN_OBJECT" },
            { label: "导出前显示文件保存路径选择对话框", type: "switch", key: "DOWNLOAD_OPTIONS.SHOW_PATH_INQUIRY_DIALOG" },
            { label: "导出完成后自动打开文件所在的目录", type: "switch", key: "DOWNLOAD_OPTIONS.SHOW_IN_FINDER" },
            { label: "图片质量", type: "range", min: 0.01, max: 1, step: 0.01, key: "DOWNLOAD_OPTIONS.IMAGE_QUALITY" },
            { label: "水平内边距", type: "number", min: 1, max: 1000, step: 1, key: "DOWNLOAD_OPTIONS.PADDING_HORIZONTAL", unit: "像素" },
            { label: "垂直内边距", type: "number", min: 1, max: 1000, step: 1, key: "DOWNLOAD_OPTIONS.PADDING_VERTICAL", unit: "像素" },
            { label: "文件名", type: "text", key: "DOWNLOAD_OPTIONS.FILENAME" },
            { label: "目录路径", type: "text", key: "DOWNLOAD_OPTIONS.FOLDER" },
            { label: "背景颜色", type: "text", key: "DOWNLOAD_OPTIONS.BACKGROUND_COLOR" },
            { label: "字体颜色", type: "text", key: "DOWNLOAD_OPTIONS.TEXT_COLOR" },
            { label: "展开节点的颜色", type: "text", key: "DOWNLOAD_OPTIONS.OPEN_CIRCLE_COLOR" },
        ),
        createBox(
            "代码块",
            { label: "启用", type: "switch", key: "ENABLE_FENCE_MARKMAP" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
            { label: "快捷键", type: "hotkey", key: "FENCE_HOTKEY" },
            { label: "代码块语言", type: "text", key: "FENCE_LANGUAGE" },
            { label: "图表默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "图表默认背景颜色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        createBox(
            "代码块默认图形",
            { label: "允许缩放图形", type: "switch", key: "DEFAULT_FENCE_OPTIONS.zoom" },
            { label: "允许平移图形", type: "switch", key: "DEFAULT_FENCE_OPTIONS.pan" },
            { label: "首次渲染分支展开等级", type: "range", min: 1, max: 6, step: 1, key: "DEFAULT_FENCE_OPTIONS.initialExpandLevel" },
            { label: "固定颜色的分支等级", type: "range", min: 1, max: 6, step: 1, key: "DEFAULT_FENCE_OPTIONS.colorFreezeLevel" },
            { label: "窗口填充率", type: "range", min: 0.5, max: 1, step: 0.01, key: "DEFAULT_FENCE_OPTIONS.fitRatio" },
            { label: "节点最大长度", type: "number", tooltip: "0 表示无限制", min: 0, max: 1000, step: 10, key: "DEFAULT_FENCE_OPTIONS.maxWidth", unit: "像素" },
            { label: "节点水平间距", type: "number", min: 0, max: 200, step: 1, key: "DEFAULT_FENCE_OPTIONS.spacingHorizontal", unit: "像素" },
            { label: "节点垂直间距", type: "number", min: 0, max: 100, step: 1, key: "DEFAULT_FENCE_OPTIONS.spacingVertical", unit: "像素" },
            { label: "节点内部边距", type: "number", min: 0, max: 100, step: 1, key: "DEFAULT_FENCE_OPTIONS.paddingX", unit: "像素" },
            { label: "动画的持续时间", type: "number", min: 0, max: 1000, step: 10, key: "DEFAULT_FENCE_OPTIONS.duration", unit: "毫秒" },
            { label: "图形高度", type: "text", key: "DEFAULT_FENCE_OPTIONS.height" },
            { label: "图形背景颜色", type: "text", key: "DEFAULT_FENCE_OPTIONS.backgroundColor" },
        ),
        createArrayBox("代码块图形默认配色方案", "DEFAULT_FENCE_OPTIONS.color"),
        createBox("模板", { type: "textarea", rows: 10, key: "FENCE_TEMPLATE" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    auto_number: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "自动编号",
            { label: "大纲", type: "switch", key: "ENABLE_OUTLINE" },
            { label: "正文", type: "switch", key: "ENABLE_CONTENT" },
            { label: "TOC", type: "switch", key: "ENABLE_TOC" },
            { label: "表格", type: "switch", key: "ENABLE_TABLE" },
            { label: "图片", type: "switch", key: "ENABLE_IMAGE" },
            { label: "代码块", type: "switch", key: "ENABLE_FENCE" },
        ),
        createBox(
            "样式",
            { label: "图片编号同时显示别名", type: "switch", key: "SHOW_IMAGE_NAME" },
            { label: "编号下标位置", type: "select", key: "ALIGN", options: { left: "在元素左侧", right: "在元素右侧", center: "在元素中间" } },
            { label: "表格编号位置", type: "select", key: "POSITION_TABLE", options: { before: "先于表格出现", after: "后于表格出现" } },
            { label: "编号字体", type: "text", key: "FONT_FAMILY" },
        ),
        createJSONBox("预设的编号格式列表", "LAYOUTS"),
        createBox("高级", { label: "导出为 HTML、PDF 时保留编号", type: "switch", key: "ENABLE_WHEN_EXPORT" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    fence_enhance: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "按钮样式",
            { label: "启用", type: "switch", key: "ENABLE_BUTTON" },
            { label: "自动隐藏", type: "switch", key: "AUTO_HIDE" },
            { label: "隐藏功能提示", type: "switch", key: "REMOVE_BUTTON_HINT" },
            { label: "不透明度", type: "range", min: 0, max: 1, step: 0.05, key: "BUTTON_OPACITY" },
            { label: "鼠标悬停不透明度", type: "range", min: 0, max: 1, step: 0.05, key: "BUTTON_OPACITY_HOVER" },
            { label: "大小", type: "text", key: "BUTTON_SIZE" },
            { label: "颜色", type: "text", key: "BUTTON_COLOR" },
            { label: "间距", type: "text", key: "BUTTON_MARGIN" },
            { label: "到顶部距离", type: "text", key: "BUTTON_TOP" },
            { label: "到右侧距离", type: "text", key: "BUTTON_RIGHT" },
            { label: "提示的保持时间", type: "number", min: 500, step: 100, key: "WAIT_RECOVER_INTERVAL", unit: "毫秒" },
        ),
        createBox(
            "功能按钮",
            { label: "复制按钮", type: "switch", key: "ENABLE_COPY" },
            { label: "调整缩进按钮", type: "switch", key: "ENABLE_INDENT" },
            { label: "折叠按钮", type: "switch", key: "ENABLE_FOLD" },
            { label: "默认折叠代码块", type: "switch", key: "DEFAULT_FOLD" },
            { label: "代码块折叠阈值", type: "number", min: 0, step: 1, key: "DEFAULT_FOLD_THRESHOLD", unit: "行" },
        ),
        createBox(
            "代码块快捷键",
            { label: "启用", type: "switch", key: "ENABLE_HOTKEY" },
            { label: "与上一行互换", type: "text", key: "SWAP_PREVIOUS_LINE" },
            { label: "与下一行互换", type: "text", key: "SWAP_NEXT_LINE" },
            { label: "复制到上一行", type: "text", key: "COPY_PREVIOUS_LINE" },
            { label: "复制到下一行", type: "text", key: "COPY_NEXT_LINE" },
            { label: "在上方插入一行", type: "text", key: "INSERT_LINE_PREVIOUS" },
            { label: "在下方插入一行", type: "text", key: "INSERT_LINE_NEXT" },
        ),
        createBox(
            "高级功能",
            { label: "代码可折叠", type: "switch", key: "ENABLE_LANGUAGE_FOLD" },
            { label: "自动对齐缩进", type: "switch", key: "INDENTED_WRAPPED_LINE" },
            { label: "通过语言栏高亮代码行", type: "switch", key: "HIGHLIGHT_BY_LANGUAGE" },
            { label: "鼠标悬停高亮代码行", type: "switch", key: "HIGHLIGHT_WHEN_HOVER" },
            { label: "代码行高亮颜色", type: "text", key: "HIGHLIGHT_LINE_COLOR" },
        ),
        createJSONBox("自定义按钮", "CUSTOM_BUTTONS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    collapse_paragraph: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "模式",
            { label: "记忆折叠状态", type: "switch", key: "RECORD_COLLAPSE" },
            { label: "严格模式", type: "switch", key: "STRICT_MODE" },
            { label: "在右键菜单中使用严格模式", type: "switch", key: "STRICT_MODE_IN_CONTEXT_MENU" },
        ),
        createBox(
            "功能修饰键",
            { label: "折叠/展开单个章节", explain: "举例：填入 ctrl，则 Clt+Click 将折叠/展开单个章节", type: "text", key: "MODIFIER_KEY.COLLAPSE_SINGLE" },
            { label: "折叠/展开父章节下所有同级的章节", type: "text", key: "MODIFIER_KEY.COLLAPSE_SIBLINGS" },
            { label: "折叠/展开当前文件所有同级的章节", type: "text", key: "MODIFIER_KEY.COLLAPSE_ALL_SIBLINGS" },
            { label: "递归折叠/展开当前章节", type: "text", key: "MODIFIER_KEY.COLLAPSE_RECURSIVE" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    collapse_list: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "列表",
            { label: "记忆折叠状态", type: "switch", key: "RECORD_COLLAPSE" },
            { label: "缩放标志颜色", type: "text", key: "TRIANGLE_COLOR" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    collapse_table: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox("表格", { label: "记忆折叠状态", type: "switch", key: "RECORD_COLLAPSE" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    truncate_text: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "快捷键",
            { label: "只保留最后若干段", type: "hotkey", key: "HIDE_FRONT_HOTKEY" },
            { label: "重新显示所有内容", type: "hotkey", key: "SHOW_ALL_HOTKEY" },
            { label: "根据当前可视范围显示", type: "hotkey", key: "HIDE_BASE_VIEW_HOTKEY" },
            { label: "保留显示的文本段数量", type: "number", key: "REMAIN_LENGTH", unit: "段" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    export_enhance: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "网络图片",
            { label: "下载并转换为 Base64 编码", type: "switch", key: "DOWNLOAD_NETWORK_IMAGE" },
            { label: "下载线程数", type: "number", key: "DOWNLOAD_THREADS" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    text_stylize: [
        createSimpleBox(
            PLUGIN_PROP_ENABLE,
            PLUGIN_PROP_NAME,
            { label: "快捷键", type: "hotkey", key: "SHOW_MODAL_HOTKEY" },
        ),
        createBox(
            "工具栏",
            { label: "背景色", type: "text", key: "MODAL_BACKGROUND_COLOR" },
            {
                label: "按钮",
                type: "select",
                key: "TOOLBAR",
                options: {
                    weight: "加粗",
                    italic: "斜体",
                    underline: "下划线",
                    throughline: "中划线",
                    overline: "上划线",
                    superScript: "上标",
                    subScript: "下标",
                    emphasis: "强调符号",
                    blur: "模糊",
                    title: "标题尺寸",
                    increaseSize: "增大尺寸",
                    decreaseSize: "减小尺寸",
                    increaseLetterSpacing: "增大字符间距",
                    decreaseLetterSpacing: "减小字符间距",
                    family: "字体",
                    foregroundColor: "前景色",
                    backgroundColor: "背景色",
                    borderColor: "边框颜色",
                    erase: "移除格式",
                    blank: "占位",
                    setBrush: "设置格式刷",
                    useBrush: "使用格式刷",
                    move: "移动工具栏",
                    close: "关闭工具栏",
                }
            }
        ),
        createBox(
            "按钮的默认值",
            { label: "前景色", type: "text", key: "DEFAULT_COLORS.FOREGROUND" },
            { label: "背景色", type: "text", key: "DEFAULT_COLORS.BACKGROUND" },
            { label: "边框颜色", type: "text", key: "DEFAULT_COLORS.BORDER" },
            { label: "格式刷", type: "text", explain: "例如：color:#FFF; font-weight:bold;", key: "DEFAULT_FORMAT_BRUSH" },
        ),
        createJSONBox("颜色按钮的预设列表", "COLOR_TABLE"),
        createJSONBox("快捷键映射的预设列表", "ACTION_HOTKEYS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    cipher: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "快捷键",
            { label: "加密", type: "hotkey", key: "ENCRYPT_HOTKEY" },
            { label: "解密", type: "hotkey", key: "DECRYPT_HOTKEY" },
        ),
        createBox("提示弹窗", { label: "加解密后弹出提示窗口", type: "switch", key: "SHOW_HINT_MODAL" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    easy_modify: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "快捷键",
            { label: "复制当前光标所在标题路径", type: "hotkey", key: "HOTKEY_COPY_FULL_PATH" },
            { label: "提升选中文段的标题等级", type: "hotkey", key: "HOTKEY_INCREASE_HEADERS_LEVEL" },
            { label: "降低选中文段的标题等级", type: "hotkey", key: "HOTKEY_DECREASE_HEADERS_LEVEL" },
            { label: "提取选区文字到新文件", type: "hotkey", key: "HOTKEY_EXTRACT_RANGE_TO_NEW_FILE" },
            { label: "插入思维导图 (mindmap)", type: "hotkey", key: "HOTKEY_INSERT_MERMAID_MINDMAP" },
            { label: "插入思维导图 (graph)", type: "hotkey", key: "HOTKEY_INSERT_MERMAID_GRAPH" },
            { label: "换行符 CRLF 替换为 LF", type: "hotkey", key: "HOTKEY_CONVERT_CRLF_TO_LF" },
            { label: "换行符 LF 替换为 CRLF", type: "hotkey", key: "HOTKEY_CONVERT_LF_TO_CRLF" },
            { label: "移除不可见字符", type: "hotkey", key: "HOTKEY_FILTER_INVISIBLE_CHARACTERS" },
            { label: "添加结尾空格", type: "hotkey", key: "HOTKEY_TRAILING_WHITE_SPACE" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    custom: [
        PLUGIN_BASE_PROP_PROTECT_LITE_SCHEMA,
        createSimpleBox({ label: "隐藏右键菜单中临时不可用的二级插件", type: "switch", key: "HIDE_DISABLE_PLUGINS" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    slash_commands: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "命令触发",
            { label: "触发文本的正则表达式", type: "text", key: "TRIGGER_REGEXP" },
            { label: "命令参数分离标识符", type: "text", key: "FUNC_PARAM_SEPARATOR", disabled: true, tooltip: PROTECTED_HINT },
            { label: "键入触发文本后", type: "select", key: "SUGGESTION_TIMING", options: { on_input: "立即显示命令列表", debounce: "400 毫秒后显示命令列表" } },
        ),
        createBox(
            "命令策略",
            { label: "匹配策略", type: "select", key: "MATCH_STRATEGY", options: { prefix: "前缀", substr: "子串", abbr: "缩写" } },
            { label: "排序策略", type: "select", key: "ORDER_STRATEGY", options: { predefined: "预定义", lexicographic: "字典序", length_based: "长度序", earliest_hit: "最早命中" } },
        ),
        createJSONBox("预设的命令列表", "COMMANDS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    right_click_menu: [
        PLUGIN_BASE_PROP_PROTECT_LITE_SCHEMA,
        createBox(
            "样式",
            { label: "显示选项快捷键", type: "switch", key: "SHOW_PLUGIN_HOTKEY" },
            { label: "动作选项添加 ⌘ 图标", type: "switch", key: "SHOW_ACTION_OPTIONS_ICON" },
            { label: "失焦不再自动隐藏", type: "switch", key: "DO_NOT_HIDE" },
            { label: "只显示插件选项", type: "switch", key: "HIDE_OTHER_OPTIONS" },
            { label: "二、三级菜单的最小宽度", type: "text", key: "MENU_MIN_WIDTH" },
        ),
        createJSONBox("自定义右键菜单", "MENUS"),
        createBox("高级", { label: "自动寻找丢失插件", type: "switch", key: "FIND_LOST_PLUGIN" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    pie_menu: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox({ label: "右键修饰键", explain: "举例：填入 ctrl，则 Ctrl+RClick 弹出菜单", type: "text", key: "MODIFIER_KEY" }),
        createJSONBox("圆盘菜单", "BUTTONS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    preferences: [
        PLUGIN_BASE_PROP_PROTECT_FULL_SCHEMA,
        createSimpleBox(
            { label: "配置页支持搜索插件英文名", type: "switch", key: "SEARCH_PLUGIN_FIXEDNAME" },
            { label: "默认的插件配置页", type: "text", key: "DEFAULT_MENU" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    file_counter: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "文本样式",
            { label: "字宽", type: "text", key: "FONT_WEIGHT" },
            { label: "颜色", type: "text", key: "COLOR" },
            { label: "背景色", type: "text", key: "BACKGROUND_COLOR" },
            { label: "前缀", type: "text", key: "BEFORE_TEXT" },
        ),
        createBox("鼠标交互", { label: "Ctrl+Wheel 横向滚动侧边栏", type: "switch", key: "CTRL_WHEEL_TO_SCROLL_SIDEBAR_MENU" }),
        createBox(
            "搜索",
            { label: "目录下最小文件数", explain: "忽略所含文件数少于 X 的目录", type: "number", key: "IGNORE_MIN_NUM" },
            { label: "最大文件", type: "number", key: "MAX_SIZE", unit: "字节" },
        ),
        createArrayBox("允许文件扩展名", "ALLOW_EXT"),
        createArrayBox("忽略目录名", "IGNORE_FOLDERS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    hotkeys: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createJSONBox("自定义快捷键列表", "CUSTOM_HOTKEYS"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    help: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    editor_width_slider: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createSimpleBox({ label: "宽度百分比", type: "number", max: 100, step: 1, key: "WIDTH_RATIO", tooltip: "-1 表示不启用", unit: "%" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    article_uploader: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createSimpleBox({ label: "隐藏右键菜单上传选项", type: "switch", key: "HIDE" }),
        createBox(
            "上传文章快捷键",
            { label: "全部", type: "hotkey", key: "UPLOAD_ALL_HOTKEY" },
            { label: "博客园", type: "hotkey", key: "UPLOAD_CNBLOG_HOTKEY" },
            { label: "WordPress", type: "hotkey", key: "UPLOAD_WORDPRESS_HOTKEY" },
            { label: "CSDN", type: "hotkey", key: "UPLOAD_CSDN_HOTKEY" },
        ),
        createBox(
            "上传选项",
            { label: "上传前弹出确认框", type: "switch", key: "upload.reconfirm" },
            { label: "Headless 模式", type: "switch", key: "upload.selenium.headless" },
        ),
        createBox(
            "WordPress",
            { label: "启用", type: "switch", key: "upload.wordpress.enabled" },
            { label: "域名/IP", type: "text", key: "upload.wordpress.hostname" },
            { label: "登录 URL", type: "text", key: "upload.wordpress.loginUrl" },
            { label: "用户名", type: "text", key: "upload.wordpress.username" },
            { label: "密码", type: "text", key: "upload.wordpress.password" },
        ),
        createBox(
            "博客园",
            { label: "启用", type: "switch", key: "upload.cnblog.enabled" },
            { label: "用户名", type: "text", key: "upload.cnblog.username" },
            { label: "密码", type: "text", key: "upload.cnblog.password" },
        ),
        createBox(
            "CSDN",
            { label: "启用", type: "switch", key: "upload.csdn.enabled" },
            { label: "Cookie", type: "text", key: "upload.csdn.cookie" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    ripgrep: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "窗口位置",
            { label: "垂直定位", type: "range", min: 0, max: 100, step: 1, key: "TOP_PERCENT" },
            { label: "宽度", type: "range", min: 0, max: 100, step: 1, key: "WIDTH_PERCENT" },
        ),
        createBox("交互", { label: "输入框为空且键入退格键时，隐藏窗口", type: "switch", key: "BACKSPACE_TO_HIDE" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    json_rpc: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "RPC Server",
            { label: "严格模式", type: "switch", key: "SERVER_OPTIONS.strict" },
            { label: "主机", type: "text", key: "SERVER_OPTIONS.host" },
            { label: "端口", type: "number", key: "SERVER_OPTIONS.port" },
            { label: "路径", type: "text", key: "SERVER_OPTIONS.path" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    updater: [
        PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox({ label: "代理 URL", type: "text", key: "PROXY" }),
        createBox(
            "自动升级",
            { label: "启用", type: "switch", key: "AUTO_UPDATE" },
            { label: "轮询时间", explain: "轮询指定时间执行升级流程", type: "number", key: "UPDATE_LOOP_INTERVAL", unit: "毫秒" },
            { label: "等待时间", explain: "软件启动后等待指定时间执行升级流程", type: "number", key: "START_UPDATE_INTERVAL", unit: "毫秒" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    test: [
        PLUGIN_BASE_PROP_LITE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    kanban: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
            { label: "严格模式", type: "switch", key: "STRICT_MODE" },
        ),
        createBox(
            "看板样式",
            { label: "宽度", type: "number", key: "KANBAN_WIDTH", unit: "像素" },
            { label: "最大高度", type: "number", key: "KANBAN_MAX_HEIGHT", unit: "像素" },
            { label: "任务描述框最大高度", type: "number", tooltip: "0 表示显示全部", key: "KANBAN_TASK_DESC_MAX_HEIGHT", unit: "em" },
            { label: "任务描述为空时隐藏描述框", type: "switch", key: "HIDE_DESC_WHEN_EMPTY" },
            { label: "看板换行显示", type: "switch", key: "WRAP" },
            { label: "Ctrl+Wheel 切换看板", type: "switch", key: "CTRL_WHEEL_TO_SWITCH" },
            { label: "支持 Markdown 语法", type: "switch", key: "ALLOW_MARKDOWN_INLINE_STYLE" },
        ),
        createArrayBox("看板颜色", "KANBAN_COLOR"),
        createArrayBox("任务颜色", "TASK_COLOR"),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    chat: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
            { label: "严格模式", type: "switch", key: "DEFAULT_OPTIONS.useStrict" },
        ),
        createBox(
            "默认选项",
            { label: "昵称", type: "switch", key: "DEFAULT_OPTIONS.showNickname" },
            { label: "头像", type: "switch", key: "DEFAULT_OPTIONS.showAvatar" },
            { label: "不显示时间", type: "switch", key: "DEFAULT_OPTIONS.notAllowShowTime" },
            { label: "支持 Markdown 语法", type: "switch", key: "DEFAULT_OPTIONS.allowMarkdown" },
            { label: "发送者昵称", type: "text", key: "DEFAULT_OPTIONS.senderNickname" },
            { label: "时间昵称", type: "text", key: "DEFAULT_OPTIONS.timeNickname" },
        ),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    timeline: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "背景颜色", type: "text", key: "BACKGROUND_COLOR" },
            { label: "标题字体颜色", type: "text", key: "TITLE_COLOR" },
            { label: "标题字体大小", type: "text", key: "TITLE_FONT_SIZE" },
            { label: "标题字宽", type: "text", key: "TITLE_FONT_WEIGHT" },
            { label: "左侧时间线颜色", type: "text", key: "LINE_COLOR" },
            { label: "左侧时间线宽度", type: "text", key: "LINE_WIDTH" },
            { label: "时间圆点颜色", type: "text", key: "CIRCLE_COLOR" },
            { label: "时间圆点直径", type: "text", key: "CIRCLE_DIAMETER" },
            { label: "时间的字体颜色", type: "text", key: "TIME_COLOR" },
            { label: "时间圆点顶部位置", type: "text", key: "CIRCLE_TOP" },
        ),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    echarts: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "背景色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        TEMPLATE_SCHEMA,
        createBox(
            "高级",
            { label: "渲染器", type: "select", key: "RENDERER", options: { canvas: "Canvas", svg: "SVG" } },
            { label: "导出格式", type: "select", key: "EXPORT_TYPE", options: { png: "PNG", jpg: "JPG", svg: "SVG" } },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    chart: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "背景色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    wavedrom: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
            { label: "安全模式", type: "switch", key: "SAFE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "背景色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    calendar: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "背景色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    abc: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "背景色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        TEMPLATE_SCHEMA,
        createJSONBox("可视化选项", "VISUAL_OPTIONS", 6),
        RESTORE_PLUGIN_SCHEMA,
    ],
    drawIO: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        createBox(
            "图表样式",
            { label: "默认高度", type: "text", key: "DEFAULT_FENCE_HEIGHT" },
            { label: "背景色", type: "text", key: "DEFAULT_FENCE_BACKGROUND_COLOR" },
        ),
        TEMPLATE_SCHEMA,
        createBox("高级", { label: "Viewer URL", type: "text", key: "RESOURCE_URI" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    marp: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "代码块",
            { label: "语言", type: "text", key: "LANGUAGE" },
            { label: "交互模式", type: "switch", key: "INTERACTIVE_MODE" },
        ),
        TEMPLATE_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    callouts: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "样式",
            { label: "高亮标题", type: "switch", key: "set_title_color" },
            { label: "阴影", type: "text", key: "box_shadow" },
        ),
        createBox("鼠标悬停", { label: "展开 Fold Callout", type: "switch", key: "hover_to_show_fold_callout" }),
        createBox(
            "默认值",
            { label: "图标字体", type: "text", key: "font_family" },
            { label: "左边线颜色", type: "text", key: "default_background_color" },
            { label: "背景颜色", type: "text", key: "default_left_line_color" },
            { label: "图标", type: "text", key: "default_icon" },
        ),
        createJSONBox("预设的 Callouts 列表", "list"),
        createBox("模板", { type: "textarea", rows: 6, key: "template" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    templater: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox({ label: "创建并自动打开新文件", type: "switch", key: "auto_open" }),
        createJSONBox("自定义模板变量列表", "template_variables"),
        createJSONBox("自定义模板列表", "template"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    chineseSymbolAutoPairer: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createBox(
            "功能选项",
            { label: "自动跳过配对符号", type: "switch", key: "auto_skip" },
            { label: "成对删除符号", type: "switch", key: "auto_delete_pair" },
            { label: "连续全角转为半角", type: "switch", key: "auto_swap" },
            { label: "自动包裹选区", type: "switch", key: "auto_surround_pair" },
            { label: "自动选中包裹内容", type: "switch", key: "auto_select_after_surround" },
        ),
        createJSONBox("自动补全的符号", "auto_pair_symbols"),
        createJSONBox("自动转换的符号", "auto_swap_symbols"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    toc: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox(
            { label: "默认开启", type: "switch", key: "default_show_toc" },
            { label: "转义标题内容", type: "switch", key: "escape_header" },
            { label: "快捷方式：右击侧边栏大纲按钮", type: "switch", key: "right_click_outline_button_to_toggle" },
        ),
        createBox(
            "大纲目录样式",
            { label: "固定到右侧的宽度", type: "range", min: 0, max: 100, step: 1, key: "width_percent_when_pin_right" },
            { label: "字体大小", type: "text", key: "toc_font_size" },
        ),
        createBox(
            "名称",
            { label: "代码块", type: "text", key: "show_name.fence" },
            { label: "图片", type: "text", key: "show_name.image" },
            { label: "表格", type: "text", key: "show_name.table" },
            { label: "链接", type: "text", key: "show_name.link" },
            { label: "公式块", type: "text", key: "show_name.math" },
        ),
        createBox(
            "目录中显示标题",
            { label: "代码块", type: "switch", key: "include_headings.fence" },
            { label: "图片", type: "switch", key: "include_headings.image" },
            { label: "表格", type: "switch", key: "include_headings.table" },
            { label: "链接", type: "switch", key: "include_headings.link" },
            { label: "公式块", type: "switch", key: "include_headings.math" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    resourceOperation: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "窗口位置",
            { label: "高度", type: "range", min: 0, max: 100, step: 1, key: "modal_height_percent" },
            { label: "宽度", type: "range", min: 0, max: 100, step: 1, key: "modal_width_percent" },
            { label: "左边框定位", type: "range", min: 0, max: 100, step: 1, key: "modal_left_percent" },
        ),
        createBox("搜索", { label: "忽略 &lt;IMG&gt; 标签", type: "switch", key: "ignore_img_html_element" }),
        createArrayBox("资源文件扩展名", "resource_suffix"),
        createSimpleBox({ label: "无扩展名文件视为资源", type: "switch", key: "collect_file_without_suffix" }),
        createArrayBox("检索文件扩展名", "markdown_suffix"),
        createArrayBox("忽略检索目录名", "ignore_folders"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    scrollBookmarker: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox(
            { label: "左键修饰键", explain: "举例：填入 alt，则 Alt+LClick 标注书签", type: "text", key: "modifier_key" },
            { label: "标注书签的同时弹出管理窗口", type: "switch", key: "auto_popup_modal" },
            { label: "持久化书签数据", type: "switch", key: "persistence" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    imageReviewer: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "样式",

            { label: "遮罩层不透明度", type: "range", min: 0, max: 1, step: 0.1, key: "mask_background_opacity" },
            { label: "图片最大宽度", type: "range", min: 0, max: 100, step: 1, key: "image_max_width" },
            { label: "图片最大高度", type: "range", min: 0, max: 100, step: 1, key: "image_max_height" },
            { label: "缩略图高度", type: "text", key: "thumbnail_height" },
            { label: "背景模糊等级", type: "number", key: "blur_level", unit: "像素" },
            { label: "缩略图额外预览图片数量", type: "number", min: 0, key: "thumbnail_scroll_padding_count" },
            { label: "瀑布流列数", type: "number", min: 0, key: "water_fall_columns" },
        ),
        createBox(
            "组件",
            { label: "缩略图导航", type: "switch", key: "show_thumbnail_nav" },
            { label: "工具栏位置", type: "select", key: "tool_position", options: { bottom: "底部", top: "顶部" } },
            {
                label: "工具栏左侧展示",
                type: "select",
                key: "show_message",
                options: { index: "图片索引", title: "图片名称", size: "图片大小" }
            },
            {
                label: "工具栏按钮",
                type: "select",
                key: "tool_function",
                minItems: 1,
                options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS,
            },
        ),
        createBox(
            "行为",
            { label: "跳过加载失败的图片", type: "switch", key: "filter_error_image" },
            {
                label: "首张图片的选择策略",
                type: "select",
                key: "first_image_strategies",
                minItems: 1,
                options: { inViewBoxImage: "当前视图中首张图片", closestViewBoxImage: "离当前视图中心最近的图片", firstImage: "文档中首张图片" }
            },
            {
                label: "缩略图的容器适应策略",
                type: "select",
                key: "thumbnail_object_fit",
                options: { fill: "拉伸适配", contain: "保持比例缩放", cover: "保持原有尺寸，裁剪超出部分", "scale-down": "保持比例缩放，当图片小于容器时图片不放大" }
            },
            { label: "轮播停留时间", type: "number", key: "play_second", unit: "秒" },
        ),
        createBox(
            "鼠标事件",
            { label: "点击空白处退出", type: "switch", key: "click_mask_to_exit" },
            { label: "LClick", type: "select", key: "mousedown_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "MClick", type: "select", key: "mousedown_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "RClick", type: "select", key: "mousedown_function.2", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Ctrl+LClick", type: "select", key: "ctrl_mousedown_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Ctrl+MClick", type: "select", key: "ctrl_mousedown_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Ctrl+RClick", type: "select", key: "ctrl_mousedown_function.2", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Shift+LClick", type: "select", key: "shift_mousedown_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Shift+MClick", type: "select", key: "shift_mousedown_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Shift+RClick", type: "select", key: "shift_mousedown_function.2", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Alt+LClick", type: "select", key: "alt_mousedown_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Alt+MClick", type: "select", key: "alt_mousedown_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Alt+RClick", type: "select", key: "alt_mousedown_function.2", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "WheelUp", type: "select", key: "wheel_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "WheelDown", type: "select", key: "wheel_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Ctrl+WheelUp", type: "select", key: "ctrl_wheel_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Ctrl+WheelDown", type: "select", key: "ctrl_wheel_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Shift+WheelUp", type: "select", key: "shift_wheel_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Shift+WheelDown", type: "select", key: "shift_wheel_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Alt+WheelUp", type: "select", key: "alt_wheel_function.0", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
            { label: "Alt+WheelDown", type: "select", key: "alt_wheel_function.1", options: CUSTOM_PLUGIN_IMAGE_REVIEWER_OPTIONS },
        ),
        createJSONBox("预设的快捷键列表", "hotkey_function"),
        createBox(
            "单次调整幅度",
            { label: "缩放比率", type: "number", key: "zoom_scale", unit: "%" },
            { label: "旋转角度", type: "number", key: "rotate_scale", unit: "度" },
            { label: "倾斜角度", type: "number", key: "skew_scale", unit: "度" },
            { label: "移动距离", type: "number", key: "translate_scale", unit: "像素" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
    markdownLint: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "窗口样式",
            { label: "宽度", type: "text", key: "modal_width" },
            { label: "最大高度", type: "text", key: "modal_max_height" },
            { label: "字体大小", type: "text", key: "modal_font_size" },
            { label: "文字行高", type: "number", key: "modal_line_height", unit: "em" },
        ),
        createBox(
            "状态指示方块",
            { label: "启用", type: "switch", key: "use_button" },
            { label: "宽度", type: "text", key: "button_width" },
            { label: "高度", type: "text", key: "button_height" },
            { label: "检测通过颜色", type: "text", key: "pass_color" },
            { label: "检测未通过颜色", type: "text", key: "error_color" },
        ),
        createBox(
            "检测与修复",
            { label: "翻译检测规则", type: "switch", key: "translate" },
            { label: "启用工具", type: "select", key: "tools", minItems: 1, options: { info: "检测信息", locate: "定位", fix: "修复" } },
            { label: "排序检测结果", type: "select", key: "result_order_by", options: { lineNumber: "按行排序", ruleName: "按检测规则排序" } },
            { label: "快捷键：修复", type: "hotkey", key: "hotkey_fix_lint_error" },
        ),
        createJSONBox("检测规则", "rule_config", 15),
        createArrayBox("自定义检测规则文件", "custom_rules"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    reopenClosedFiles: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createSimpleBox({ label: "自动恢复未关闭标签", type: "switch", key: "auto_reopen_when_init" }),
        RESTORE_PLUGIN_SCHEMA,
    ],
    quickButton: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        createBox(
            "按钮样式",
            { label: "大小", type: "text", key: "button_size" },
            { label: "圆角半径", type: "text", key: "button_border_radius" },
            { label: "阴影", type: "text", key: "button_box_shadow" },
            { label: "间距", type: "text", key: "button_gap" },
            { label: "距右边框", type: "text", key: "position_right" },
            { label: "距底边框", type: "text", key: "position_bottom" },
        ),
        createSimpleBox(
            { label: "支持右键点击", type: "switch", key: "support_right_click" },
            { label: "隐藏提示信息", type: "switch", key: "hide_button_hint" },
        ),
        createJSONBox("预设的按钮列表", "buttons"),
        RESTORE_PLUGIN_SCHEMA,
    ],
    blockSideBySide: [
        CUSTOM_PLUGIN_BASE_PROP_FULL_SCHEMA,
        RESTORE_PLUGIN_SCHEMA,
    ],
    redirectLocalRootUrl: [
        CUSTOM_PLUGIN_BASE_PROP_LITE_SCHEMA,
        createSimpleBox(
            { label: "资源根目录", type: "text", key: "root" },
            { label: "过滤正则表达式", type: "text", key: "filter_regexp" },
        ),
        RESTORE_PLUGIN_SCHEMA,
    ],
}

module.exports = {
    ...SETTING_SCHEMAS
}