<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TyporaPluginInstaller.Gui</RootNamespace>
    <AssemblyName>TyporaPluginInstaller</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TyporaPluginInstaller.Core\TyporaPluginInstaller.Core.csproj" />
  </ItemGroup>

</Project>
