version: 2
updates:
  - package-ecosystem: npm
    directory: /develop
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
