/**
 * This code contains workarounds and hacks to address specific behaviors of Typora.
 * Understanding the intricacies may be challenging. This documentation outlines the implementation logic for future modifications.
 *
 * Core Idea: Simplify the problem by initially focusing on single-line selections.
 *
 * 1. Single-Line Selection Scenarios:
 *    Consider the example: `123<span style="color:#FF0000;">abc</span>defg`
 *    Four selection possibilities exist:
 *      a. No selection.
 *      b. Standard selection (e.g., "efg" - anything not covered by c and d).
 *      c. Selection within an existing styled span (e.g., "abc").
 *      d. Selection encompassing an entire styled span (e.g., `<span style="color:#FF0000;">abc</span>`).
 *
 * 2. Handling Simple Scenarios (a, b, and c):
 *      a. No selection: Insert an empty styled span (`<span style="XXX"></span>`) at the cursor.
 *      b. Standard selection: Wrap the selected text (e.g., "efg") with a styled span: `<span style="XXX">efg</span>`. Then, insert it back into the document.
 *      c. Selection within a span: Transform the selection into scenario d.  For example, "abc" becomes `<span style="color:#FF0000;">abc</span>`.
 *
 * 3. Handling Scenario d (Selecting an Existing Span):
 *      a. Deconstruct the example `123<span style="color:#FF0000;">abc</span>defg` into:
 *         - `beforeText`: "123" (Text before the span)
 *         - `innerText`: "abc" (Text inside the span)
 *         - `outerText`: `<span style="color:#FF0000;">abc</span>` (The entire span element)
 *         - `styleObject`: A JavaScript object representing the CSS style of the span (e.g., `{ color: '#FF0000' }`)
 *      b. Modify the `styleObject` as needed to apply the new styling.
 *      c. Reconstruct the `outerText` using the updated `innerText` and `styleObject`. Insert this new `outerText` back into the document.
 *      d. Use the `beforeText` and modified `styleObject` to determine the final position of the `innerText`.
 *         Move the bookmark (selection) to correctly re-select the `innerText`.
 *      e. The above steps are encapsulated in the `setInlineStyle` function.
 *
 * 4. Handling Multi-Line Selections:
 *    When the user selects text across multiple lines and potentially multiple tags, the process involves:
 *      a. Breaking the multi-line selection into individual lines.
 *      b. Applying the `setInlineStyle` function to each line.
 *
 *    Implementation details for multi-line handling (`getSelectedRanges` function):
 *      a. Use `TreeWalker` along with the `range` object's `commonAncestorContainer`, `startContainer`, and `endContainer` to get an array of all selected nodes (`nodeList`).
 *      b. Filter out unnecessary text nodes within `<span md-inline="softbreak" class="md-softbreak"> </span>` tags (generated by shift+enter for soft line breaks).
 *      c. Split the `nodeList` into lines based on `node.classList.contains("md-softbreak")` (soft breaks) and `!!node.getAttribute("cid")` (hard breaks).
 *         Use `range.setStart(startContainer, startOffset)` and `range.setEnd(endContainer, endOffset)` to define the selection range for each line.
 *      d. The `startContainer` and `endContainer` will be TEXT_NODEs. Filter out any ELEMENT_NODEs to get an array of lines (`selectLines`).
 *      e. `selectLines` is a 2D array where each element is an array of TEXT_NODEs for a single line.
 *         The `startContainer` and `endContainer` correspond to the first and last TEXT_NODEs of each line, respectively.
 *      f. Special handling is required for the first and last lines, as they might not be fully selected.
 *      g. After splitting, you'll have the `startContainer`, `startOffset`, `endContainer`, and `endOffset` for each individual line.
 *
 * 5. Addressing Typora's DOM Manipulation Issues:
 *    Typora modifies the paragraph's `innerHTML` after inserting a span, invalidating the previously obtained TEXT_NODEs in the ranges. The solution is:
 *      a. The `textContent` of the paragraph remains unchanged after the span insertion. Record the position of the old TEXT_NODEs in the document *before* inserting the span.
 *      b. After Typora updates the DOM, use the recorded positions to find the *new* TEXT_NODEs.
 *      c. Replace the old TEXT_NODEs with the new TEXT_NODEs in the ranges.
 *      d. Now the (updated) TEXT_NODEs are valid. Proceed to call `setInlineStyle`.
 *      e. The above process is implemented in `setMultilineStyle`.  `recordTextPosition` handles the recording, and `renewRange` handles the replacement.
 *
 * 6. Overall Styling Process:
 *    The main function `setStyle` orchestrates the entire process, calling `getSelectedRanges`, `setMultilineStyle`, and the helper functions as needed.
 */
class StyleSetter {
  constructor(utils, formatBrushString) {
    this.utils = utils
    this.formatBrushObj = this.parseStyleString(formatBrushString)
  }

  setStyle = ({ toggleMap, deleteMap, mergeMap, upsertMap, replaceMap, hook, moveBookmark = true, rememberFormat = false }) => {
    const args = { toggleMap, deleteMap, mergeMap, upsertMap, replaceMap, hook, moveBookmark, rememberFormat }
    const ranges = this.getSelectedRanges()
    if (!ranges || ranges.length === 0) {
      console.debug("Has not ranges")
    } else if (ranges.length === 1) {
      this.setInlineStyle(args)
    } else {
      this.setMultilineStyle(ranges, args)
    }
  }

  setBrush = () => this.setStyle({ upsertMap: {}, rememberFormat: true })

  useBrush = () => this.setStyle({ replaceMap: this.formatBrushObj })

  /**
   * There are four possible user selection scenarios, for example: `123<span style="color:#FF0000;">abc</span>defg`
   *   a. No selection.
   *   b. Standard selection (e.g., "efg").
   *   c. Selection within an existing styled span (e.g., "abc"): Modify the outer text.
   *   d. Selection encompassing an entire styled span (e.g., `<span style="color:#FF0000;">abc</span>`): Modify the inner text.
   */
  setInlineStyle = ({ toggleMap, deleteMap, mergeMap, upsertMap, replaceMap, hook, moveBookmark, rememberFormat }) => {
    const selection = window.getSelection()
    const activeElement = document.activeElement.tagName
    if (File.isLocked || "INPUT" === activeElement || "TEXTAREA" === activeElement || !selection.rangeCount) return

    const { range, node, bookmark } = this.utils.getRangy()
    if (!node) return
    const el = File.editor.findElemById(node.cid)
    const line = el.rawText()

    const beforeText = line.substring(0, bookmark.start)
    let innerText = line.substring(bookmark.start, bookmark.end)
    let outerText = innerText
    let wrapType = ""
    let newBookmark = null

    const matcher = new RegExp(/^<span\s?(style="(?<styles>.*?)")?>(?<wrapper>.*?)<\/span>$/)
    const suffix = "</span>"

    const innerSelected = () => {
      if (line.substring(bookmark.start, bookmark.end + suffix.length).endsWith(suffix)) {
        const result = beforeText.match(/<span .*?>/g)
        if (!result) return
        const last = result.at(-1)
        if (last && beforeText.endsWith(last)) {
          return last
        }
      }
    }

    const outerSelected = () => innerText.match(matcher)?.groups?.wrapper

    const innerRegexResult = innerSelected()
    // Scenario c
    if (innerRegexResult) {
      wrapType = "inner"
      newBookmark = {
        containerNode: bookmark.containerNode,
        start: bookmark.start - innerRegexResult.length,
        end: bookmark.end + suffix.length,
      }
      range.moveToBookmark(newBookmark)
      range.select()
      outerText = line.substring(newBookmark.start, newBookmark.end)
    } else {
      const outerRegexResult = outerSelected()
      // Scenario d
      if (outerRegexResult) {
        wrapType = "outer"
        innerText = outerRegexResult
      }
    }

    let styleMap = {}
    if (replaceMap !== undefined) {
      styleMap = replaceMap
    } else {
      const regexpResult = outerText.match(matcher)
      const styles = regexpResult?.groups?.styles
      if (styles) {
        styleMap = this.parseStyleString(styles)
      }
      if (upsertMap) {
        Object.assign(styleMap, upsertMap)
      }
      if (toggleMap) {
        Object.entries(toggleMap).forEach(([key, value]) => {
          if (styleMap[key] === value) {
            delete styleMap[key]
          } else {
            styleMap[key] = value
          }
        })
      }
      if (mergeMap) {
        Object.entries(mergeMap).forEach(([key, value]) => {
          const origin = styleMap[key]
          if (origin === value) {
            delete styleMap[key]
          } else if (origin === undefined) {
            styleMap[key] = value
          } else {
            const set = new Set(origin.split(" "))
            if (set.has(value)) {
              set.delete(value)
            } else {
              set.add(value)
            }
            styleMap[key] = Array.from(set.keys()).join(" ")
          }
        })
      }
      if (deleteMap) {
        Object.keys(deleteMap).forEach(key => delete styleMap[key])
      }
    }
    if (typeof hook === "function") {
      hook(styleMap)
    }
    if (rememberFormat) {
      this.formatBrushObj = styleMap
    }

    const style = Object.entries(styleMap).map(([key, value]) => `${key}:${value};`).join(" ")
    const prefix = (style === "") ? "" : `<span style="${style}">`
    const content = (style === "") ? innerText : prefix + innerText + suffix
    this.utils.insertText(null, content, false)

    if (moveBookmark) {
      setTimeout(() => {
        let start = 0
        // Scenario c
        if (wrapType === "inner") {
          start = newBookmark.start
          // Scenario b or Scenario d
        } else if (wrapType === "outer" || (wrapType === "" && innerText !== "")) {
          start = bookmark.start
          // Scenario a
        } else if (wrapType === "" && innerText === "") {
          start = beforeText.length
        }

        const { range, bookmark: bk } = this.utils.getRangy()
        bk.start = start + prefix.length
        bk.end = bk.start + innerText.length
        range.moveToBookmark(bk)
        range.select()
      }, 100)
    }
  }

  setMultilineStyle = (ranges, args) => {
    // TODO: html element needs add class "md-expand"
    const originMoveBookmark = false
    // const originMoveBookmark = args.moveBookmark

    this.recordTextPosition(ranges)
    const selection = window.getSelection()

    let startBeforeContent, endBeforeContent
    if (originMoveBookmark) {
      ({ startBeforeContent, endBeforeContent } = this.recordBookmark(selection))
    }

    args.moveBookmark = false
    for (const rangeObj of ranges) {
      this.renewRange(rangeObj)
      const range = document.createRange()
      range.setStart(rangeObj.startContainer, rangeObj.startOffset)
      range.setEnd(rangeObj.endContainer, rangeObj.endOffset)
      selection.removeAllRanges()
      selection.addRange(range)
      this.setInlineStyle(args)
    }

    if (originMoveBookmark) {
      setTimeout(() => {
        const startRange = ranges[0]
        const endRange = ranges.at(-1)

        startRange.beforeContent = startBeforeContent
        endRange.beforeContent = endBeforeContent
        this.renewRange(startRange)
        this.renewRange(endRange)

        const range = document.createRange()
        range.setStartBefore(startRange.startContainer)
        range.setEndBefore(endRange.startContainer)
        selection.removeAllRanges()
        selection.addRange(range)
      }, 100)
    }
  }

  getSelectedRanges = () => {
    const range = window.getSelection().getRangeAt(0)
    const nodes = this.collectNodesInSelection(range)
    return this.splitRangesByLines(nodes, range)
  }

  recordBookmark = selection => {
    const range = selection.getRangeAt(0)
    const { endContainer, endOffset, startContainer, startOffset } = range

    range.setStart(startContainer, 0)
    range.setEnd(startContainer, startOffset)
    selection.removeAllRanges()
    selection.addRange(range)
    const startBeforeContent = range.toString()

    range.setStart(endContainer, 0)
    range.setEnd(endContainer, endOffset)
    selection.removeAllRanges()
    selection.addRange(range)
    const endBeforeContent = range.toString()
    return { startBeforeContent, endBeforeContent }
  }

  renewRange = range => {
    const { beforeContent, afterContent, cid } = range
    const target = this.utils.entities.querySelectorInWrite(`[cid="${cid}"]`)
    const TEXTs = this.extractTextNodes(target)

    let textContent = ""
    for (let i = 0; i < TEXTs.length; i++) {
      let TEXT = TEXTs[i]
      textContent += TEXT.textContent
      if (textContent === beforeContent) {
        range.startContainer = TEXTs[i + 1]
      }
      if (textContent === afterContent) {
        range.endContainer = TEXTs[i + 1] || TEXT
        break
      }
    }
  }

  recordTextPosition = ranges => {
    for (const range of ranges) {
      const startTEXT = range.startContainer
      const endTEXT = range.endContainer
      const el = startTEXT.parentElement
      const target = el.closest("[cid]")
      const TEXTs = this.extractTextNodes(target)

      for (let i = 0; i < TEXTs.length; i++) {
        const TEXT = TEXTs[i]
        if (TEXT === startTEXT) {
          range.beforeContent = TEXTs.slice(0, i).map(e => e.textContent).join("")
          range.cid = target.getAttribute("cid")
        }
        if (TEXT === endTEXT) {
          range.afterContent = TEXTs.slice(0, i).map(e => e.textContent).join("")
        }
      }
    }
  }

  collectNodesInSelection = range => {
    const { startContainer, endContainer, commonAncestorContainer } = range

    const nodes = []
    const walker = document.createTreeWalker(
      commonAncestorContainer,
      NodeFilter.SHOW_ELEMENT + NodeFilter.SHOW_TEXT,
      { acceptNode: () => NodeFilter.FILTER_ACCEPT },
    )
    while (walker.currentNode !== startContainer) {
      walker.nextNode()
    }
    while (true) {
      const currentNode = walker.currentNode
      nodes.push(currentNode)
      if (currentNode === endContainer) {
        break
      }
      walker.nextNode()
    }
    return nodes
  }

  splitRangesByLines = (nodes, range) => {
    const isText = node => node && node.nodeType === document.TEXT_NODE
    const isElement = node => node && node.nodeType === document.ELEMENT_NODE
    const isSoftBreak = node => isElement(node) && node.classList.contains("md-softbreak")
    const isHardBreak = node => isElement(node) && node.getAttribute("cid")
    const isBreak = node => isSoftBreak(node) || isHardBreak(node)
    const splitArray = (array, separateFn) => {
      return array.reduce((acc, cur) => {
        if (separateFn(cur)) {
          acc.push([])
        } else {
          if (acc.length === 0) {
            acc.push([])
          }
          acc.at(-1).push(cur)
        }
        return acc
      }, [])
    }

    if (nodes.length <= 1 || !nodes.some(isBreak)) {
      return [range]
    }

    const validTextNodes = nodes.filter((node, idx) => !(isText(node) && isSoftBreak(nodes[idx - 1])))
    const selectLines = splitArray(validTextNodes, isBreak).map(line => line.filter(isText)).filter(line => line.length)

    const startLineTexts = selectLines.shift()
    const endLineTexts = selectLines.pop() || startLineTexts
    const startLineLastText = startLineTexts.at(-1)
    const endLineFirstText = endLineTexts[0]

    const createRange = (startContainer, startOffset, endContainer, endOffset) => ({ startContainer, startOffset, endContainer, endOffset })
    const firstRange = createRange(range.startContainer, range.startOffset, startLineLastText, startLineLastText.length)
    const middleRanges = selectLines.map(line => createRange(line[0], 0, line.at(-1), line.at(-1).length))
    const ranges = [firstRange, ...middleRanges]
    const isEndWithBreak = isText(nodes.at(-1)) && isSoftBreak(nodes.at(-2))
    if (!isEndWithBreak) {
      ranges.push(createRange(endLineFirstText, 0, range.endContainer, range.endOffset))
    }

    const isCollapsed = range => range.startContainer === range.endContainer && range.startOffset === range.endOffset
    const isEqual = (a, b) => (
      a && b && a.startContainer === b.startContainer && a.startOffset === b.startOffset
      && a.endContainer === b.endContainer && a.endOffset === b.endOffset
    )
    return ranges.filter((range, idx) => !isCollapsed(range) && !isEqual(ranges[idx - 1], range))
  }

  extractTextNodes = element => {
    const nodes = []
    if (!element) return nodes

    const acceptNode = n => {
      if (n.nodeType === document.ELEMENT_NODE && (n.classList.contains("md-raw-inline") || n.classList.contains("md-softbreak"))) {
        return NodeFilter.FILTER_REJECT
      }
      return n.nodeType === document.TEXT_NODE ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP
    }
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_ALL, { acceptNode })
    while (walker.nextNode()) {
      nodes.push(walker.currentNode)
    }

    return nodes
  }

  parseStyleString = styleString => {
    const obj = {}
    styleString.split(";").forEach(s => {
      const [attr, value] = s.trim().split(":")
      if (attr && value) {
        obj[attr] = value
      }
    })
    return obj
  }
}

module.exports = StyleSetter
