<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TyporaPluginInstaller.Cli</RootNamespace>
    <AssemblyName>typora-plugin-installer-cli</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TyporaPluginInstaller.Core\TyporaPluginInstaller.Core.csproj" />
  </ItemGroup>

</Project>
