var A=Object.defineProperty;var X=Object.getOwnPropertyDescriptor;var Y=Object.getOwnPropertyNames;var q=Object.prototype.hasOwnProperty;var L=e=>{throw TypeError(e)};var F=(e,t)=>{for(var n in t)A(e,n,{get:t[n],enumerable:!0})},J=(e,t,n,i)=>{if(t&&typeof t=="object"||typeof t=="function")for(let r of Y(t))!q.call(e,r)&&r!==n&&A(e,r,{get:()=>t[r],enumerable:!(i=X(t,r))||i.enumerable});return e};var H=e=>J(A({},"__esModule",{value:!0}),e);var j=(e,t,n)=>t.has(e)||L("Cannot "+n);var d=(e,t,n)=>(j(e,t,"read from private field"),n?n.call(e):t.get(e)),$=(e,t,n)=>t.has(e)?L("Cannot add the same private member more than once"):t instanceof WeakSet?t.add(e):t.set(e,n),p=(e,t,n,i)=>(j(e,t,"write to private field"),i?i.call(e,n):t.set(e,n),n);var ue={};F(ue,{TomlDate:()=>E,TomlError:()=>c,parse:()=>U,stringify:()=>K});module.exports=H(ue);var Q=/^(\d{4}-\d{2}-\d{2})?[T ]?(?:(\d{2}):\d{2}(?::\d{2}(?:\.\d+)?)?)?(Z|[-+]\d{2}:\d{2})?$/i,x,y,h,k=class k extends Date{constructor(n){let i=!0,r=!0,o="Z";if(typeof n=="string"){let l=n.match(Q);l?(l[1]||(i=!1,n=`0000-01-01T${n}`),r=!!l[2],r&&n[10]===" "&&(n=n.replace(" ","T")),l[2]&&+l[2]>23?n="":(o=l[3]||null,n=n.toUpperCase(),!o&&r&&(n+="Z"))):n=""}super(n);$(this,x,!1);$(this,y,!1);$(this,h,null);isNaN(this.getTime())||(p(this,x,i),p(this,y,r),p(this,h,o))}isDateTime(){return d(this,x)&&d(this,y)}isLocal(){return!d(this,x)||!d(this,y)||!d(this,h)}isDate(){return d(this,x)&&!d(this,y)}isTime(){return d(this,y)&&!d(this,x)}isValid(){return d(this,x)||d(this,y)}toISOString(){let n=super.toISOString();if(this.isDate())return n.slice(0,10);if(this.isTime())return n.slice(11,23);if(d(this,h)===null)return n.slice(0,-1);if(d(this,h)==="Z")return n;let i=+d(this,h).slice(1,3)*60+ +d(this,h).slice(4,6);return i=d(this,h)[0]==="-"?i:-i,new Date(this.getTime()-i*6e4).toISOString().slice(0,-1)+d(this,h)}static wrapAsOffsetDateTime(n,i="Z"){let r=new k(n);return p(r,h,i),r}static wrapAsLocalDateTime(n){let i=new k(n);return p(i,h,null),i}static wrapAsLocalDate(n){let i=new k(n);return p(i,y,!1),p(i,h,null),i}static wrapAsLocalTime(n){let i=new k(n);return p(i,x,!1),p(i,h,null),i}};x=new WeakMap,y=new WeakMap,h=new WeakMap;var E=k;function W(e,t){let n=e.slice(0,t).split(/\r\n|\n|\r/g);return[n.length,n.pop().length+1]}function B(e,t,n){let i=e.split(/\r\n|\n|\r/g),r="",o=(Math.log10(t+1)|0)+1;for(let l=t-1;l<=t+1;l++){let u=i[l-1];u&&(r+=l.toString().padEnd(o," "),r+=":  ",r+=u,r+=`
`,l===t&&(r+=" ".repeat(o+n+2),r+=`^
`))}return r}var c=class extends Error{line;column;codeblock;constructor(t,n){let[i,r]=W(n.toml,n.ptr),o=B(n.toml,i,r);super(`Invalid TOML document: ${t}

${o}`,n),this.line=i,this.column=r,this.codeblock=o}};var ee=/^((0x[0-9a-fA-F](_?[0-9a-fA-F])*)|(([+-]|0[ob])?\d(_?\d)*))$/,te=/^[+-]?\d(_?\d)*(\.\d(_?\d)*)?([eE][+-]?\d(_?\d)*)?$/,ne=/^[+-]?0[0-9_]/;function N(e,t){let n=e[t++],i=n,r=n==="'",o=n===e[t]&&n===e[t+1];o&&(e[t+=2]===`
`?t++:e[t]==="\r"&&e[t+1]===`
`&&(t+=2));let l="",u=t,a=0;for(let f=t;f<e.length;f++)if(n=e[f],o&&(n===`
`||n==="\r"&&e[f+1]===`
`))a=a&&3;else{if(n<" "&&n!=="	"||n==="\x7F")throw new c("control characters are not allowed in strings",{toml:e,ptr:f});if((!a||a===3)&&n===i&&(!o||e[f+1]===i&&e[f+2]===i))return o&&(e[f+3]===i&&f++,e[f+3]===i&&f++),[a?l:l+e.slice(u,f),f+(o?3:1)];if(!a)!r&&n==="\\"&&(l+=e.slice(u,u=f),a=1);else if(a===1)if(n==="x"||n==="u"||n==="U"){let s=0,m=n==="x"?2:n==="u"?4:8;for(let w=0;w<m;w++,f++){let g=e.charCodeAt(f+1),T=g>=48&&g<=57?g-48:g>=65&&g<=70?g-65+10:g>=97&&g<=102?g-97+10:-1;if(T<0)throw new c("invalid non-hex character in unicode escape",{toml:e,ptr:f+1});s=s<<4|T}if(s<0||s>1114111||s>=55296&&s<=57343)throw new c("invalid unicode escape",{toml:e,ptr:f});l+=String.fromCodePoint(s),u=f+1,a=0}else if(n===" "||n==="	")a=2;else{if(n==="b")l+="\b";else if(n==="t")l+="	";else if(n==="n")l+=`
`;else if(n==="f")l+="\f";else if(n==="r")l+="\r";else if(n==="e")l+="\x1B";else if(n==='"')l+='"';else if(n==="\\")l+="\\";else throw new c("unrecognized escape sequence",{toml:e,ptr:f});u=f+1,a=0}else if(n!==" "&&n!=="	"){if(a===2)throw new c("invalid escape: only line-ending whitespace may be escaped",{toml:e,ptr:u});a=!r&&n==="\\"?1:0,u=f}}throw new c("unfinished string",{toml:e,ptr:t})}function R(e,t,n,i){if(e==="true")return!0;if(e==="false")return!1;if(e==="-inf")return-1/0;if(e==="inf"||e==="+inf")return 1/0;if(e==="nan"||e==="+nan"||e==="-nan")return NaN;if(e==="-0")return i?0n:0;let r=ee.test(e);if(r||te.test(e)){if(ne.test(e))throw new c("leading zeroes are not allowed",{toml:t,ptr:n});e=e.replace(/_/g,"");let l=+e;if(isNaN(l))throw new c("invalid number",{toml:t,ptr:n});if(r){if((r=!Number.isSafeInteger(l))&&!i)throw new c("integer value cannot be represented losslessly",{toml:t,ptr:n});(r||i===!0)&&(l=BigInt(e))}return l}let o=new E(e);if(!o.isValid())throw new c("invalid value",{toml:t,ptr:n});return o}function I(e,t=0,n=e.length){let i=e.indexOf(`
`,t);return e[i-1]==="\r"&&i--,i<=n?i:-1}function O(e,t){for(let n=t;n<e.length;n++){let i=e[n];if(i===`
`)return n;if(i==="\r"&&e[n+1]===`
`)return n+1;if(i<" "&&i!=="	"||i==="\x7F")throw new c("control characters are not allowed in comments",{toml:e,ptr:t})}return e.length}function b(e,t,n,i){let r;for(;;){for(;(r=e[t])===" "||r==="	"||!n&&(r===`
`||r==="\r"&&e[t+1]===`
`);)t++;if(i||r!=="#")break;t=O(e,t)}return t}function Z(e,t,n,i,r=!1){if(!i)return t=I(e,t),t<0?e.length:t;for(let o=t;o<e.length;o++){let l=e[o];if(l==="#")o=I(e,o);else{if(l===n)return o+1;if(l===i||r&&(l===`
`||l==="\r"&&e[o+1]===`
`))return o}}throw new c("cannot find end of structure",{toml:e,ptr:t})}function ie(e,t,n){let i=e.slice(t,n),r=i.indexOf("#");return r>-1&&(O(e,r),i=i.slice(0,r)),[i.trimEnd(),r]}function S(e,t,n,i,r){if(i===0)throw new c("document contains excessively nested structures. aborting.",{toml:e,ptr:t});let o=e[t];if(o==="["||o==="{"){let[a,f]=o==="["?v(e,t,i,r):z(e,t,i,r);if(n){if(f=b(e,f),e[f]===",")f++;else if(e[f]!==n)throw new c("expected comma or end of structure",{toml:e,ptr:f})}return[a,f]}if(o==='"'||o==="'"){let[a,f]=N(e,t);if(n){if(f=b(e,f),e[f]&&e[f]!==","&&e[f]!==n&&e[f]!==`
`&&e[f]!=="\r")throw new c("unexpected character encountered",{toml:e,ptr:f});e[f]===","&&f++}return[a,f]}let l=Z(e,t,",",n),u=ie(e,t,l-(e[l-1]===","?1:0));if(!u[0])throw new c("incomplete key-value declaration: no value specified",{toml:e,ptr:t});return n&&u[1]>-1&&(l=b(e,t+u[1]),e[l]===","&&l++),[R(u[0],e,t,r),l]}var re=/^[a-zA-Z0-9-_]+[ \t]*$/;function D(e,t,n="="){let i=t-1,r=[],o=e.indexOf(n,t);if(o<0)throw new c("incomplete key-value: cannot find end of key",{toml:e,ptr:t});do{let l=e[t=++i];if(l!==" "&&l!=="	")if(l==='"'||l==="'"){if(l===e[t+1]&&l===e[t+2])throw new c("multiline strings are not allowed in keys",{toml:e,ptr:t});let[u,a]=N(e,t);i=e.indexOf(".",a);let f=e.slice(a,i<0||i>o?o:i),s=I(f);if(s>-1)throw new c("newlines are not allowed in keys",{toml:e,ptr:t+i+s});if(f.trimStart())throw new c("found extra tokens after the string part",{toml:e,ptr:a});if(o<a&&(o=e.indexOf(n,a),o<0))throw new c("incomplete key-value: cannot find end of key",{toml:e,ptr:t});r.push(u)}else{i=e.indexOf(".",t);let u=e.slice(t,i<0||i>o?o:i);if(!re.test(u))throw new c("only letter, numbers, dashes and underscores are allowed in keys",{toml:e,ptr:t});r.push(u.trimEnd())}}while(i+1&&i<o);return[r,b(e,o+1,!0,!0)]}function z(e,t,n,i){let r={},o=new Set,l;for(t++;(l=e[t++])!=="}"&&l;){if(l===",")throw new c("expected value, found comma",{toml:e,ptr:t-1});if(l==="#")t=O(e,t);else if(l!==" "&&l!=="	"&&l!==`
`&&l!=="\r"){let u,a=r,f=!1,[s,m]=D(e,t-1);for(let T=0;T<s.length;T++){if(T&&(a=f?a[u]:a[u]={}),u=s[T],(f=Object.hasOwn(a,u))&&(typeof a[u]!="object"||o.has(a[u])))throw new c("trying to redefine an already defined value",{toml:e,ptr:t});!f&&u==="__proto__"&&Object.defineProperty(a,u,{enumerable:!0,configurable:!0,writable:!0})}if(f)throw new c("trying to redefine an already defined value",{toml:e,ptr:t});let[w,g]=S(e,m,"}",n-1,i);o.add(w),a[u]=w,t=g}}if(!l)throw new c("unfinished table encountered",{toml:e,ptr:t});return[r,t]}function v(e,t,n,i){let r=[],o;for(t++;(o=e[t++])!=="]"&&o;){if(o===",")throw new c("expected value, found comma",{toml:e,ptr:t-1});if(o==="#")t=O(e,t);else if(o!==" "&&o!=="	"&&o!==`
`&&o!=="\r"){let l=S(e,t-1,"]",n-1,i);r.push(l[0]),t=l[1]}}if(!o)throw new c("unfinished array encountered",{toml:e,ptr:t});return[r,t]}function M(e,t,n,i){var f,s;let r=t,o=n,l,u=!1,a;for(let m=0;m<e.length;m++){if(m){if(r=u?r[l]:r[l]={},o=(a=o[l]).c,i===0&&(a.t===1||a.t===2))return null;if(a.t===2){let w=r.length-1;r=r[w],o=o[w].c}}if(l=e[m],(u=Object.hasOwn(r,l))&&((f=o[l])==null?void 0:f.t)===0&&((s=o[l])!=null&&s.d))return null;u||(l==="__proto__"&&(Object.defineProperty(r,l,{enumerable:!0,configurable:!0,writable:!0}),Object.defineProperty(o,l,{enumerable:!0,configurable:!0,writable:!0})),o[l]={t:m<e.length-1&&i===2?3:i,d:!1,i:0,c:{}})}if(a=o[l],a.t!==i&&!(i===1&&a.t===3)||(i===2&&(a.d||(a.d=!0,r[l]=[]),r[l].push(r={}),a.c[a.i++]=a={t:1,d:!1,i:0,c:{}}),a.d))return null;if(a.d=!0,i===1)r=u?r[l]:r[l]={};else if(i===0&&u)return null;return[l,r,a.c]}function U(e,{maxDepth:t=1e3,integersAsBigInt:n}={}){let i={},r={},o=i,l=r;for(let u=b(e,0);u<e.length;){if(e[u]==="["){let a=e[++u]==="[",f=D(e,u+=+a,"]");if(a){if(e[f[1]-1]!=="]")throw new c("expected end of table declaration",{toml:e,ptr:f[1]-1});f[1]++}let s=M(f[0],i,r,a?2:1);if(!s)throw new c("trying to redefine an already defined table or value",{toml:e,ptr:u});l=s[2],o=s[1],u=f[1]}else{let a=D(e,u),f=M(a[0],o,l,0);if(!f)throw new c("trying to redefine an already defined table or value",{toml:e,ptr:u});let s=S(e,a[1],void 0,t,n);f[1][f[0]]=s[0],u=s[1]}if(u=b(e,u,!0),e[u]&&e[u]!==`
`&&e[u]!=="\r")throw new c("each key-value declaration must be followed by an end-of-line",{toml:e,ptr:u});u=b(e,u)}return i}var G=/^[a-z0-9-_]+$/i;function _(e){let t=typeof e;if(t==="object"){if(Array.isArray(e))return"array";if(e instanceof Date)return"date"}return t}function le(e){for(let t=0;t<e.length;t++)if(_(e[t])!=="object")return!1;return e.length!=0}function P(e){return JSON.stringify(e).replace(/\x7f/g,"\\u007f")}function V(e,t,n,i){if(n===0)throw new Error("Could not stringify the object: maximum object depth exceeded");if(t==="number")return isNaN(e)?"nan":e===1/0?"inf":e===-1/0?"-inf":Number.isInteger(e)&&(i||!Number.isSafeInteger(e))?e.toFixed(1):e.toString();if(t==="bigint"||t==="boolean")return e.toString();if(t==="string")return P(e);if(t==="date"){if(isNaN(e.getTime()))throw new TypeError("cannot serialize invalid date");return e.toISOString()}if(t==="object")return oe(e,n,i);if(t==="array")return fe(e,n,i)}function oe(e,t,n){let i=Object.keys(e);if(i.length===0)return"{}";let r="{ ";for(let o=0;o<i.length;o++){let l=i[o];o&&(r+=", "),r+=G.test(l)?l:P(l),r+=" = ",r+=V(e[l],_(e[l]),t-1,n)}return r+" }"}function fe(e,t,n){if(e.length===0)return"[]";let i="[ ";for(let r=0;r<e.length;r++){if(r&&(i+=", "),e[r]===null||e[r]===void 0)throw new TypeError("arrays cannot contain null or undefined values");i+=V(e[r],_(e[r]),t-1,n)}return i+" ]"}function ae(e,t,n,i){if(n===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let r="";for(let o=0;o<e.length;o++)r+=`${r&&`
`}[[${t}]]
`,r+=C(0,e[o],t,n,i);return r}function C(e,t,n,i,r){if(i===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let o="",l="",u=Object.keys(t);for(let a=0;a<u.length;a++){let f=u[a];if(t[f]!==null&&t[f]!==void 0){let s=_(t[f]);if(s==="symbol"||s==="function")throw new TypeError(`cannot serialize values of type '${s}'`);let m=G.test(f)?f:P(f);if(s==="array"&&le(t[f]))l+=(l&&`
`)+ae(t[f],n?`${n}.${m}`:m,i-1,r);else if(s==="object"){let w=n?`${n}.${m}`:m;l+=(l&&`
`)+C(w,t[f],w,i-1,r)}else o+=m,o+=" = ",o+=V(t[f],s,i,r),o+=`
`}}return e&&(o||!l)&&(o=o?`[${e}]
${o}`:`[${e}]`),o&&l?`${o}
${l}`:o||l}function K(e,{maxDepth:t=1e3,numbersAsFloat:n=!1}={}){if(_(e)!=="object")throw new TypeError("stringify can only be called with an object");let i=C(0,e,"",t,n);return i[i.length-1]!==`
`?i+`
`:i}0&&(module.exports={TomlDate,TomlError,parse,stringify});
