var A=Object.defineProperty;var q=Object.getOwnPropertyDescriptor;var F=Object.getOwnPropertyNames;var J=Object.prototype.hasOwnProperty;var L=e=>{throw TypeError(e)};var H=(e,n)=>{for(var t in n)A(e,t,{get:n[t],enumerable:!0})},Q=(e,n,t,i)=>{if(n&&typeof n=="object"||typeof n=="function")for(let l of F(n))!J.call(e,l)&&l!==t&&A(e,l,{get:()=>n[l],enumerable:!(i=q(n,l))||i.enumerable});return e};var W=e=>Q(A({},"__esModule",{value:!0}),e);var R=(e,n,t)=>n.has(e)||L("Cannot "+t);var s=(e,n,t)=>(R(e,n,"read from private field"),t?t.call(e):n.get(e)),$=(e,n,t)=>n.has(e)?L("Cannot add the same private member more than once"):n instanceof WeakSet?n.add(e):n.set(e,t),g=(e,n,t,i)=>(R(e,n,"write to private field"),i?i.call(e,t):n.set(e,t),t);var me={};H(me,{TomlDate:()=>T,TomlError:()=>c,parse:()=>U,stringify:()=>X});module.exports=W(me);function B(e,n){let t=e.slice(0,n).split(/\r\n|\n|\r/g);return[t.length,t.pop().length+1]}function ee(e,n,t){let i=e.split(/\r\n|\n|\r/g),l="",o=(Math.log10(n+1)|0)+1;for(let r=n-1;r<=n+1;r++){let f=i[r-1];f&&(l+=r.toString().padEnd(o," "),l+=":  ",l+=f,l+=`
`,r===n&&(l+=" ".repeat(o+t+2),l+=`^
`))}return l}var c=class extends Error{line;column;codeblock;constructor(n,t){let[i,l]=B(t.toml,t.ptr),o=ee(t.toml,i,l);super(`Invalid TOML document: ${n}

${o}`,t),this.line=i,this.column=l,this.codeblock=o}};function ne(e,n){let t=0;for(;e[n-++t]==="\\";);return--t&&t%2}function k(e,n=0,t=e.length){let i=e.indexOf(`
`,n);return e[i-1]==="\r"&&i--,i<=t?i:-1}function b(e,n){for(let t=n;t<e.length;t++){let i=e[t];if(i===`
`)return t;if(i==="\r"&&e[t+1]===`
`)return t+1;if(i<" "&&i!=="	"||i==="\x7F")throw new c("control characters are not allowed in comments",{toml:e,ptr:n})}return e.length}function h(e,n,t,i){let l;for(;(l=e[n])===" "||l==="	"||!t&&(l===`
`||l==="\r"&&e[n+1]===`
`);)n++;return i||l!=="#"?n:h(e,b(e,n),t)}function Z(e,n,t,i,l=!1){if(!i)return n=k(e,n),n<0?e.length:n;for(let o=n;o<e.length;o++){let r=e[o];if(r==="#")o=k(e,o);else{if(r===t)return o+1;if(r===i||l&&(r===`
`||r==="\r"&&e[o+1]===`
`))return o}}throw new c("cannot find end of structure",{toml:e,ptr:n})}function I(e,n){let t=e[n],i=t===e[n+1]&&e[n+1]===e[n+2]?e.slice(n,n+3):t;n+=i.length-1;do n=e.indexOf(i,++n);while(n>-1&&t!=="'"&&ne(e,n));return n>-1&&(n+=i.length,i.length>1&&(e[n]===t&&n++,e[n]===t&&n++)),n}var te=/^(\d{4}-\d{2}-\d{2})?[T ]?(?:(\d{2}):\d{2}(?::\d{2}(?:\.\d+)?)?)?(Z|[-+]\d{2}:\d{2})?$/i,p,x,m,E=class E extends Date{constructor(t){let i=!0,l=!0,o="Z";if(typeof t=="string"){let r=t.match(te);r?(r[1]||(i=!1,t=`0000-01-01T${t}`),l=!!r[2],l&&t[10]===" "&&(t=t.replace(" ","T")),r[2]&&+r[2]>23?t="":(o=r[3]||null,t=t.toUpperCase(),!o&&l&&(t+="Z"))):t=""}super(t);$(this,p,!1);$(this,x,!1);$(this,m,null);isNaN(this.getTime())||(g(this,p,i),g(this,x,l),g(this,m,o))}isDateTime(){return s(this,p)&&s(this,x)}isLocal(){return!s(this,p)||!s(this,x)||!s(this,m)}isDate(){return s(this,p)&&!s(this,x)}isTime(){return s(this,x)&&!s(this,p)}isValid(){return s(this,p)||s(this,x)}toISOString(){let t=super.toISOString();if(this.isDate())return t.slice(0,10);if(this.isTime())return t.slice(11,23);if(s(this,m)===null)return t.slice(0,-1);if(s(this,m)==="Z")return t;let i=+s(this,m).slice(1,3)*60+ +s(this,m).slice(4,6);return i=s(this,m)[0]==="-"?i:-i,new Date(this.getTime()-i*6e4).toISOString().slice(0,-1)+s(this,m)}static wrapAsOffsetDateTime(t,i="Z"){let l=new E(t);return g(l,m,i),l}static wrapAsLocalDateTime(t){let i=new E(t);return g(i,m,null),i}static wrapAsLocalDate(t){let i=new E(t);return g(i,x,!1),g(i,m,null),i}static wrapAsLocalTime(t){let i=new E(t);return g(i,p,!1),g(i,m,null),i}};p=new WeakMap,x=new WeakMap,m=new WeakMap;var T=E;var ie=/^((0x[0-9a-fA-F](_?[0-9a-fA-F])*)|(([+-]|0[ob])?\d(_?\d)*))$/,re=/^[+-]?\d(_?\d)*(\.\d(_?\d)*)?([eE][+-]?\d(_?\d)*)?$/,le=/^[+-]?0[0-9_]/,oe=/^[0-9a-f]{2,8}$/i,j={b:"\b",t:"	",n:`
`,f:"\f",r:"\r",e:"\x1B",'"':'"',"\\":"\\"};function D(e,n=0,t=e.length){let i=e[n]==="'",l=e[n++]===e[n]&&e[n]===e[n+1];l&&(t-=2,e[n+=2]==="\r"&&n++,e[n]===`
`&&n++);let o=0,r,f="",u=n;for(;n<t-1;){let a=e[n++];if(a===`
`||a==="\r"&&e[n]===`
`){if(!l)throw new c("newlines are not allowed in strings",{toml:e,ptr:n-1})}else if(a<" "&&a!=="	"||a==="\x7F")throw new c("control characters are not allowed in strings",{toml:e,ptr:n-1});if(r){if(r=!1,a==="x"||a==="u"||a==="U"){let d=e.slice(n,n+=a==="x"?2:a==="u"?4:8);if(!oe.test(d))throw new c("invalid unicode escape",{toml:e,ptr:o});try{f+=String.fromCodePoint(parseInt(d,16))}catch{throw new c("invalid unicode escape",{toml:e,ptr:o})}}else if(l&&(a===`
`||a===" "||a==="	"||a==="\r")){if(n=h(e,n-1,!0),e[n]!==`
`&&e[n]!=="\r")throw new c("invalid escape: only line-ending whitespace may be escaped",{toml:e,ptr:o});n=h(e,n)}else if(a in j)f+=j[a];else throw new c("unrecognized escape sequence",{toml:e,ptr:o});u=n}else!i&&a==="\\"&&(o=n-1,r=!0,f+=e.slice(u,o))}return f+e.slice(u,t-1)}function z(e,n,t,i){if(e==="true")return!0;if(e==="false")return!1;if(e==="-inf")return-1/0;if(e==="inf"||e==="+inf")return 1/0;if(e==="nan"||e==="+nan"||e==="-nan")return NaN;if(e==="-0")return i?0n:0;let l=ie.test(e);if(l||re.test(e)){if(le.test(e))throw new c("leading zeroes are not allowed",{toml:n,ptr:t});e=e.replace(/_/g,"");let r=+e;if(isNaN(r))throw new c("invalid number",{toml:n,ptr:t});if(l){if((l=!Number.isSafeInteger(r))&&!i)throw new c("integer value cannot be represented losslessly",{toml:n,ptr:t});(l||i===!0)&&(r=BigInt(e))}return r}let o=new T(e);if(!o.isValid())throw new c("invalid value",{toml:n,ptr:t});return o}function fe(e,n,t){let i=e.slice(n,t),l=i.indexOf("#");return l>-1&&(b(e,l),i=i.slice(0,l)),[i.trimEnd(),l]}function O(e,n,t,i,l){if(i===0)throw new c("document contains excessively nested structures. aborting.",{toml:e,ptr:n});let o=e[n];if(o==="["||o==="{"){let[u,a]=o==="["?v(e,n,i,l):M(e,n,i,l);if(t){if(a=h(e,a),e[a]===",")a++;else if(e[a]!==t)throw new c("expected comma or end of structure",{toml:e,ptr:a})}return[u,a]}let r;if(o==='"'||o==="'"){r=I(e,n);let u=D(e,n,r);if(t){if(r=h(e,r),e[r]&&e[r]!==","&&e[r]!==t&&e[r]!==`
`&&e[r]!=="\r")throw new c("unexpected character encountered",{toml:e,ptr:r});r+=+(e[r]===",")}return[u,r]}r=Z(e,n,",",t);let f=fe(e,n,r-+(e[r-1]===","));if(!f[0])throw new c("incomplete key-value declaration: no value specified",{toml:e,ptr:n});return t&&f[1]>-1&&(r=h(e,n+f[1]),r+=+(e[r]===",")),[z(f[0],e,n,l),r]}var ae=/^[a-zA-Z0-9-_]+[ \t]*$/;function N(e,n,t="="){let i=n-1,l=[],o=e.indexOf(t,n);if(o<0)throw new c("incomplete key-value: cannot find end of key",{toml:e,ptr:n});do{let r=e[n=++i];if(r!==" "&&r!=="	")if(r==='"'||r==="'"){if(r===e[n+1]&&r===e[n+2])throw new c("multiline strings are not allowed in keys",{toml:e,ptr:n});let f=I(e,n);if(f<0)throw new c("unfinished string encountered",{toml:e,ptr:n});i=e.indexOf(".",f);let u=e.slice(f,i<0||i>o?o:i),a=k(u);if(a>-1)throw new c("newlines are not allowed in keys",{toml:e,ptr:n+i+a});if(u.trimStart())throw new c("found extra tokens after the string part",{toml:e,ptr:f});if(o<f&&(o=e.indexOf(t,f),o<0))throw new c("incomplete key-value: cannot find end of key",{toml:e,ptr:n});l.push(D(e,n,f))}else{i=e.indexOf(".",n);let f=e.slice(n,i<0||i>o?o:i);if(!ae.test(f))throw new c("only letter, numbers, dashes and underscores are allowed in keys",{toml:e,ptr:n});l.push(f.trimEnd())}}while(i+1&&i<o);return[l,h(e,o+1,!0,!0)]}function M(e,n,t,i){let l={},o=new Set,r;for(n++;(r=e[n++])!=="}"&&r;){if(r===",")throw new c("expected value, found comma",{toml:e,ptr:n-1});if(r==="#")n=b(e,n);else if(r!==" "&&r!=="	"&&r!==`
`&&r!=="\r"){let f,u=l,a=!1,[d,w]=N(e,n-1);for(let _=0;_<d.length;_++){if(_&&(u=a?u[f]:u[f]={}),f=d[_],(a=Object.hasOwn(u,f))&&(typeof u[f]!="object"||o.has(u[f])))throw new c("trying to redefine an already defined value",{toml:e,ptr:n});!a&&f==="__proto__"&&Object.defineProperty(u,f,{enumerable:!0,configurable:!0,writable:!0})}if(a)throw new c("trying to redefine an already defined value",{toml:e,ptr:n});let[y,Y]=O(e,w,"}",t-1,i);o.add(y),u[f]=y,n=Y}}if(!r)throw new c("unfinished table encountered",{toml:e,ptr:n});return[l,n]}function v(e,n,t,i){let l=[],o;for(n++;(o=e[n++])!=="]"&&o;){if(o===",")throw new c("expected value, found comma",{toml:e,ptr:n-1});if(o==="#")n=b(e,n);else if(o!==" "&&o!=="	"&&o!==`
`&&o!=="\r"){let r=O(e,n-1,"]",t-1,i);l.push(r[0]),n=r[1]}}if(!o)throw new c("unfinished array encountered",{toml:e,ptr:n});return[l,n]}function G(e,n,t,i){var a,d;let l=n,o=t,r,f=!1,u;for(let w=0;w<e.length;w++){if(w){if(l=f?l[r]:l[r]={},o=(u=o[r]).c,i===0&&(u.t===1||u.t===2))return null;if(u.t===2){let y=l.length-1;l=l[y],o=o[y].c}}if(r=e[w],(f=Object.hasOwn(l,r))&&((a=o[r])==null?void 0:a.t)===0&&((d=o[r])!=null&&d.d))return null;f||(r==="__proto__"&&(Object.defineProperty(l,r,{enumerable:!0,configurable:!0,writable:!0}),Object.defineProperty(o,r,{enumerable:!0,configurable:!0,writable:!0})),o[r]={t:w<e.length-1&&i===2?3:i,d:!1,i:0,c:{}})}if(u=o[r],u.t!==i&&!(i===1&&u.t===3)||(i===2&&(u.d||(u.d=!0,l[r]=[]),l[r].push(l={}),u.c[u.i++]=u={t:1,d:!1,i:0,c:{}}),u.d))return null;if(u.d=!0,i===1)l=f?l[r]:l[r]={};else if(i===0&&f)return null;return[r,l,u.c]}function U(e,{maxDepth:n=1e3,integersAsBigInt:t}={}){let i={},l={},o=i,r=l;for(let f=h(e,0);f<e.length;){if(e[f]==="["){let u=e[++f]==="[",a=N(e,f+=+u,"]");if(u){if(e[a[1]-1]!=="]")throw new c("expected end of table declaration",{toml:e,ptr:a[1]-1});a[1]++}let d=G(a[0],i,l,u?2:1);if(!d)throw new c("trying to redefine an already defined table or value",{toml:e,ptr:f});r=d[2],o=d[1],f=a[1]}else{let u=N(e,f),a=G(u[0],o,r,0);if(!a)throw new c("trying to redefine an already defined table or value",{toml:e,ptr:f});let d=O(e,u[1],void 0,n,t);a[1][a[0]]=d[0],f=d[1]}if(f=h(e,f,!0),e[f]&&e[f]!==`
`&&e[f]!=="\r")throw new c("each key-value declaration must be followed by an end-of-line",{toml:e,ptr:f});f=h(e,f)}return i}var K=/^[a-z0-9-_]+$/i;function S(e){let n=typeof e;if(n==="object"){if(Array.isArray(e))return"array";if(e instanceof Date)return"date"}return n}function ue(e){for(let n=0;n<e.length;n++)if(S(e[n])!=="object")return!1;return e.length!=0}function V(e){return JSON.stringify(e).replace(/\x7f/g,"\\u007f")}function C(e,n,t,i){if(t===0)throw new Error("Could not stringify the object: maximum object depth exceeded");if(n==="number")return isNaN(e)?"nan":e===1/0?"inf":e===-1/0?"-inf":i&&Number.isInteger(e)?e.toFixed(1):e.toString();if(n==="bigint"||n==="boolean")return e.toString();if(n==="string")return V(e);if(n==="date"){if(isNaN(e.getTime()))throw new TypeError("cannot serialize invalid date");return e.toISOString()}if(n==="object")return ce(e,t,i);if(n==="array")return de(e,t,i)}function ce(e,n,t){let i=Object.keys(e);if(i.length===0)return"{}";let l="{ ";for(let o=0;o<i.length;o++){let r=i[o];o&&(l+=", "),l+=K.test(r)?r:V(r),l+=" = ",l+=C(e[r],S(e[r]),n-1,t)}return l+" }"}function de(e,n,t){if(e.length===0)return"[]";let i="[ ";for(let l=0;l<e.length;l++){if(l&&(i+=", "),e[l]===null||e[l]===void 0)throw new TypeError("arrays cannot contain null or undefined values");i+=C(e[l],S(e[l]),n-1,t)}return i+" ]"}function se(e,n,t,i){if(t===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let l="";for(let o=0;o<e.length;o++)l+=`${l&&`
`}[[${n}]]
`,l+=P(0,e[o],n,t,i);return l}function P(e,n,t,i,l){if(i===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let o="",r="",f=Object.keys(n);for(let u=0;u<f.length;u++){let a=f[u];if(n[a]!==null&&n[a]!==void 0){let d=S(n[a]);if(d==="symbol"||d==="function")throw new TypeError(`cannot serialize values of type '${d}'`);let w=K.test(a)?a:V(a);if(d==="array"&&ue(n[a]))r+=(r&&`
`)+se(n[a],t?`${t}.${w}`:w,i-1,l);else if(d==="object"){let y=t?`${t}.${w}`:w;r+=(r&&`
`)+P(y,n[a],y,i-1,l)}else o+=w,o+=" = ",o+=C(n[a],d,i,l),o+=`
`}}return e&&(o||!r)&&(o=o?`[${e}]
${o}`:`[${e}]`),o&&r?`${o}
${r}`:o||r}function X(e,{maxDepth:n=1e3,numbersAsFloat:t=!1}={}){if(S(e)!=="object")throw new TypeError("stringify can only be called with an object");let i=P(0,e,"",n,t);return i[i.length-1]!==`
`?i+`
`:i}0&&(module.exports={TomlDate,TomlError,parse,stringify});
