var I=Object.defineProperty;var H=Object.getOwnPropertyDescriptor;var Q=Object.getOwnPropertyNames;var W=Object.prototype.hasOwnProperty;var j=e=>{throw TypeError(e)};var B=(e,n,t)=>n in e?I(e,n,{enumerable:!0,configurable:!0,writable:!0,value:t}):e[n]=t;var ee=(e,n)=>{for(var t in n)I(e,t,{get:n[t],enumerable:!0})},ne=(e,n,t,i)=>{if(n&&typeof n=="object"||typeof n=="function")for(let l of Q(n))!W.call(e,l)&&l!==t&&I(e,l,{get:()=>n[l],enumerable:!(i=H(n,l))||i.enumerable});return e};var te=e=>ne(I({},"__esModule",{value:!0}),e);var N=(e,n,t)=>B(e,typeof n!="symbol"?n+"":n,t),z=(e,n,t)=>n.has(e)||j("Cannot "+t);var m=(e,n,t)=>(z(e,n,"read from private field"),t?t.call(e):n.get(e)),$=(e,n,t)=>n.has(e)?j("Cannot add the same private member more than once"):n instanceof WeakSet?n.add(e):n.set(e,t),g=(e,n,t,i)=>(z(e,n,"write to private field"),i?i.call(e,t):n.set(e,t),t);var ge={};ee(ge,{TomlDate:()=>E,TomlError:()=>c,parse:()=>X,stringify:()=>q});module.exports=te(ge);function ie(e,n){let t=e.slice(0,n).split(/\r\n|\n|\r/g);return[t.length,t.pop().length+1]}function le(e,n,t){let i=e.split(/\r\n|\n|\r/g),l="",o=(Math.log10(n+1)|0)+1;for(let r=n-1;r<=n+1;r++){let f=i[r-1];f&&(l+=r.toString().padEnd(o," "),l+=":  ",l+=f,l+=`
`,r===n&&(l+=" ".repeat(o+t+2),l+=`^
`))}return l}var c=class extends Error{constructor(t,i){let[l,o]=ie(i.toml,i.ptr),r=le(i.toml,l,o);super(`Invalid TOML document: ${t}

${r}`,i);N(this,"line");N(this,"column");N(this,"codeblock");this.line=l,this.column=o,this.codeblock=r}};function x(e,n=0,t=e.length){let i=e.indexOf(`
`,n);return e[i-1]==="\r"&&i--,i<=t?i:-1}function O(e,n){for(let t=n;t<e.length;t++){let i=e[t];if(i===`
`)return t;if(i==="\r"&&e[t+1]===`
`)return t+1;if(i<" "&&i!=="	"||i==="\x7F")throw new c("control characters are not allowed in comments",{toml:e,ptr:n})}return e.length}function h(e,n,t,i){let l;for(;(l=e[n])===" "||l==="	"||!t&&(l===`
`||l==="\r"&&e[n+1]===`
`);)n++;return i||l!=="#"?n:h(e,O(e,n),t)}function C(e,n,t,i,l=!1){if(!i)return n=x(e,n),n<0?e.length:n;for(let o=n;o<e.length;o++){let r=e[o];if(r==="#")o=x(e,o);else{if(r===t)return o+1;if(r===i||l&&(r===`
`||r==="\r"&&e[o+1]===`
`))return o}}throw new c("cannot find end of structure",{toml:e,ptr:n})}function D(e,n){let t=e[n],i=t===e[n+1]&&e[n+1]===e[n+2]?e.slice(n,n+3):t;n+=i.length-1;do n=e.indexOf(i,++n);while(n>-1&&t!=="'"&&e[n-1]==="\\"&&(e[n-2]!=="\\"||e[n-3]==="\\"));return n>-1&&(n+=i.length,i.length>1&&(e[n]===t&&n++,e[n]===t&&n++)),n}var re=/^(\d{4}-\d{2}-\d{2})?[T ]?(?:(\d{2}):\d{2}:\d{2}(?:\.\d+)?)?(Z|[-+]\d{2}:\d{2})?$/i,p,y,w,b=class b extends Date{constructor(t){let i=!0,l=!0,o="Z";if(typeof t=="string"){let r=t.match(re);r?(r[1]||(i=!1,t=`0000-01-01T${t}`),l=!!r[2],l&&t[10]===" "&&(t=t.replace(" ","T")),r[2]&&+r[2]>23?t="":(o=r[3]||null,t=t.toUpperCase(),!o&&l&&(t+="Z"))):t=""}super(t);$(this,p,!1);$(this,y,!1);$(this,w,null);isNaN(this.getTime())||(g(this,p,i),g(this,y,l),g(this,w,o))}isDateTime(){return m(this,p)&&m(this,y)}isLocal(){return!m(this,p)||!m(this,y)||!m(this,w)}isDate(){return m(this,p)&&!m(this,y)}isTime(){return m(this,y)&&!m(this,p)}isValid(){return m(this,p)||m(this,y)}toISOString(){let t=super.toISOString();if(this.isDate())return t.slice(0,10);if(this.isTime())return t.slice(11,23);if(m(this,w)===null)return t.slice(0,-1);if(m(this,w)==="Z")return t;let i=+m(this,w).slice(1,3)*60+ +m(this,w).slice(4,6);return i=m(this,w)[0]==="-"?i:-i,new Date(this.getTime()-i*6e4).toISOString().slice(0,-1)+m(this,w)}static wrapAsOffsetDateTime(t,i="Z"){let l=new b(t);return g(l,w,i),l}static wrapAsLocalDateTime(t){let i=new b(t);return g(i,w,null),i}static wrapAsLocalDate(t){let i=new b(t);return g(i,y,!1),g(i,w,null),i}static wrapAsLocalTime(t){let i=new b(t);return g(i,p,!1),g(i,w,null),i}};p=new WeakMap,y=new WeakMap,w=new WeakMap;var E=b;var oe=/^((0x[0-9a-fA-F](_?[0-9a-fA-F])*)|(([+-]|0[ob])?\d(_?\d)*))$/,fe=/^[+-]?\d(_?\d)*(\.\d(_?\d)*)?([eE][+-]?\d(_?\d)*)?$/,ae=/^[+-]?0[0-9_]/,ue=/^[0-9a-f]{4,8}$/i,K={b:"\b",t:"	",n:`
`,f:"\f",r:"\r",'"':'"',"\\":"\\"};function A(e,n=0,t=e.length){let i=e[n]==="'",l=e[n++]===e[n]&&e[n]===e[n+1];l&&(t-=2,e[n+=2]==="\r"&&n++,e[n]===`
`&&n++);let o=0,r,f="",u=n;for(;n<t-1;){let a=e[n++];if(a===`
`||a==="\r"&&e[n]===`
`){if(!l)throw new c("newlines are not allowed in strings",{toml:e,ptr:n-1})}else if(a<" "&&a!=="	"||a==="\x7F")throw new c("control characters are not allowed in strings",{toml:e,ptr:n-1});if(r){if(r=!1,a==="u"||a==="U"){let d=e.slice(n,n+=a==="u"?4:8);if(!ue.test(d))throw new c("invalid unicode escape",{toml:e,ptr:o});try{f+=String.fromCodePoint(parseInt(d,16))}catch(s){throw new c("invalid unicode escape",{toml:e,ptr:o})}}else if(l&&(a===`
`||a===" "||a==="	"||a==="\r")){if(n=h(e,n-1,!0),e[n]!==`
`&&e[n]!=="\r")throw new c("invalid escape: only line-ending whitespace may be escaped",{toml:e,ptr:o});n=h(e,n)}else if(a in K)f+=K[a];else throw new c("unrecognized escape sequence",{toml:e,ptr:o});u=n}else!i&&a==="\\"&&(o=n-1,r=!0,f+=e.slice(u,o))}return f+e.slice(u,t-1)}function M(e,n,t,i){if(e==="true")return!0;if(e==="false")return!1;if(e==="-inf")return-1/0;if(e==="inf"||e==="+inf")return 1/0;if(e==="nan"||e==="+nan"||e==="-nan")return NaN;if(e==="-0")return i?BigInt(0):0;let l=oe.test(e);if(l||fe.test(e)){if(ae.test(e))throw new c("leading zeroes are not allowed",{toml:n,ptr:t});e=e.replace(/_/g,"");let r=+e;if(isNaN(r))throw new c("invalid number",{toml:n,ptr:t});if(l){if((l=!Number.isSafeInteger(r))&&!i)throw new c("integer value cannot be represented losslessly",{toml:n,ptr:t});(l||i===!0)&&(r=BigInt(e))}return r}let o=new E(e);if(!o.isValid())throw new c("invalid value",{toml:n,ptr:t});return o}function ce(e,n,t,i){let l=e.slice(n,t),o=l.indexOf("#");o>-1&&(O(e,o),l=l.slice(0,o));let r=l.trimEnd();if(!i){let f=l.indexOf(`
`,r.length);if(f>-1)throw new c("newlines are not allowed in inline tables",{toml:e,ptr:n+f})}return[r,o]}function S(e,n,t,i,l){if(i===0)throw new c("document contains excessively nested structures. aborting.",{toml:e,ptr:n});let o=e[n];if(o==="["||o==="{"){let[u,a]=o==="["?G(e,n,i,l):v(e,n,i,l),d=t?C(e,a,",",t):a;if(a-d&&t==="}"){let s=x(e,a,d);if(s>-1)throw new c("newlines are not allowed in inline tables",{toml:e,ptr:s})}return[u,d]}let r;if(o==='"'||o==="'"){r=D(e,n);let u=A(e,n,r);if(t){if(r=h(e,r,t!=="]"),e[r]&&e[r]!==","&&e[r]!==t&&e[r]!==`
`&&e[r]!=="\r")throw new c("unexpected character encountered",{toml:e,ptr:r});r+=+(e[r]===",")}return[u,r]}r=C(e,n,",",t);let f=ce(e,n,r-+(e[r-1]===","),t==="]");if(!f[0])throw new c("incomplete key-value declaration: no value specified",{toml:e,ptr:n});return t&&f[1]>-1&&(r=h(e,n+f[1]),r+=+(e[r]===",")),[M(f[0],e,n,l),r]}var de=/^[a-zA-Z0-9-_]+[ \t]*$/;function V(e,n,t="="){let i=n-1,l=[],o=e.indexOf(t,n);if(o<0)throw new c("incomplete key-value: cannot find end of key",{toml:e,ptr:n});do{let r=e[n=++i];if(r!==" "&&r!=="	")if(r==='"'||r==="'"){if(r===e[n+1]&&r===e[n+2])throw new c("multiline strings are not allowed in keys",{toml:e,ptr:n});let f=D(e,n);if(f<0)throw new c("unfinished string encountered",{toml:e,ptr:n});i=e.indexOf(".",f);let u=e.slice(f,i<0||i>o?o:i),a=x(u);if(a>-1)throw new c("newlines are not allowed in keys",{toml:e,ptr:n+i+a});if(u.trimStart())throw new c("found extra tokens after the string part",{toml:e,ptr:f});if(o<f&&(o=e.indexOf(t,f),o<0))throw new c("incomplete key-value: cannot find end of key",{toml:e,ptr:n});l.push(A(e,n,f))}else{i=e.indexOf(".",n);let f=e.slice(n,i<0||i>o?o:i);if(!de.test(f))throw new c("only letter, numbers, dashes and underscores are allowed in keys",{toml:e,ptr:n});l.push(f.trimEnd())}}while(i+1&&i<o);return[l,h(e,o+1,!0,!0)]}function v(e,n,t,i){let l={},o=new Set,r,f=0;for(n++;(r=e[n++])!=="}"&&r;){let u={toml:e,ptr:n-1};if(r===`
`)throw new c("newlines are not allowed in inline tables",u);if(r==="#")throw new c("inline tables cannot contain comments",u);if(r===",")throw new c("expected key-value, found comma",u);if(r!==" "&&r!=="	"){let a,d=l,s=!1,[T,F]=V(e,n-1);for(let k=0;k<T.length;k++){if(k&&(d=s?d[a]:d[a]={}),a=T[k],(s=Object.hasOwn(d,a))&&(typeof d[a]!="object"||o.has(d[a])))throw new c("trying to redefine an already defined value",{toml:e,ptr:n});!s&&a==="__proto__"&&Object.defineProperty(d,a,{enumerable:!0,configurable:!0,writable:!0})}if(s)throw new c("trying to redefine an already defined value",{toml:e,ptr:n});let[Z,J]=S(e,F,"}",t-1,i);o.add(Z),d[a]=Z,n=J,f=e[n-1]===","?n-1:0}}if(f)throw new c("trailing commas are not allowed in inline tables",{toml:e,ptr:f});if(!r)throw new c("unfinished table encountered",{toml:e,ptr:n});return[l,n]}function G(e,n,t,i){let l=[],o;for(n++;(o=e[n++])!=="]"&&o;){if(o===",")throw new c("expected value, found comma",{toml:e,ptr:n-1});if(o==="#")n=O(e,n);else if(o!==" "&&o!=="	"&&o!==`
`&&o!=="\r"){let r=S(e,n-1,"]",t-1,i);l.push(r[0]),n=r[1]}}if(!o)throw new c("unfinished array encountered",{toml:e,ptr:n});return[l,n]}function U(e,n,t,i){var a,d;let l=n,o=t,r,f=!1,u;for(let s=0;s<e.length;s++){if(s){if(l=f?l[r]:l[r]={},o=(u=o[r]).c,i===0&&(u.t===1||u.t===2))return null;if(u.t===2){let T=l.length-1;l=l[T],o=o[T].c}}if(r=e[s],(f=Object.hasOwn(l,r))&&((a=o[r])==null?void 0:a.t)===0&&((d=o[r])!=null&&d.d))return null;f||(r==="__proto__"&&(Object.defineProperty(l,r,{enumerable:!0,configurable:!0,writable:!0}),Object.defineProperty(o,r,{enumerable:!0,configurable:!0,writable:!0})),o[r]={t:s<e.length-1&&i===2?3:i,d:!1,i:0,c:{}})}if(u=o[r],u.t!==i&&!(i===1&&u.t===3)||(i===2&&(u.d||(u.d=!0,l[r]=[]),l[r].push(l={}),u.c[u.i++]=u={t:1,d:!1,i:0,c:{}}),u.d))return null;if(u.d=!0,i===1)l=f?l[r]:l[r]={};else if(i===0&&f)return null;return[r,l,u.c]}function X(e,{maxDepth:n=1e3,integersAsBigInt:t}={}){let i={},l={},o=i,r=l;for(let f=h(e,0);f<e.length;){if(e[f]==="["){let u=e[++f]==="[",a=V(e,f+=+u,"]");if(u){if(e[a[1]-1]!=="]")throw new c("expected end of table declaration",{toml:e,ptr:a[1]-1});a[1]++}let d=U(a[0],i,l,u?2:1);if(!d)throw new c("trying to redefine an already defined table or value",{toml:e,ptr:f});r=d[2],o=d[1],f=a[1]}else{let u=V(e,f),a=U(u[0],o,r,0);if(!a)throw new c("trying to redefine an already defined table or value",{toml:e,ptr:f});let d=S(e,u[1],void 0,n,t);a[1][a[0]]=d[0],f=d[1]}if(f=h(e,f,!0),e[f]&&e[f]!==`
`&&e[f]!=="\r")throw new c("each key-value declaration must be followed by an end-of-line",{toml:e,ptr:f});f=h(e,f)}return i}var Y=/^[a-z0-9-_]+$/i;function _(e){let n=typeof e;if(n==="object"){if(Array.isArray(e))return"array";if(e instanceof Date)return"date"}return n}function me(e){for(let n=0;n<e.length;n++)if(_(e[n])!=="object")return!1;return e.length!=0}function L(e){return JSON.stringify(e).replace(/\x7f/g,"\\u007f")}function P(e,n,t,i){if(t===0)throw new Error("Could not stringify the object: maximum object depth exceeded");if(n==="number")return isNaN(e)?"nan":e===1/0?"inf":e===-1/0?"-inf":i&&Number.isInteger(e)?e.toFixed(1):e.toString();if(n==="bigint"||n==="boolean")return e.toString();if(n==="string")return L(e);if(n==="date"){if(isNaN(e.getTime()))throw new TypeError("cannot serialize invalid date");return e.toISOString()}if(n==="object")return se(e,t,i);if(n==="array")return we(e,t,i)}function se(e,n,t){let i=Object.keys(e);if(i.length===0)return"{}";let l="{ ";for(let o=0;o<i.length;o++){let r=i[o];o&&(l+=", "),l+=Y.test(r)?r:L(r),l+=" = ",l+=P(e[r],_(e[r]),n-1,t)}return l+" }"}function we(e,n,t){if(e.length===0)return"[]";let i="[ ";for(let l=0;l<e.length;l++){if(l&&(i+=", "),e[l]===null||e[l]===void 0)throw new TypeError("arrays cannot contain null or undefined values");i+=P(e[l],_(e[l]),n-1,t)}return i+" ]"}function he(e,n,t,i){if(t===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let l="";for(let o=0;o<e.length;o++)l+=`[[${n}]]
`,l+=R(e[o],n,t,i),l+=`

`;return l}function R(e,n,t,i){if(t===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let l="",o="",r=Object.keys(e);for(let f=0;f<r.length;f++){let u=r[f];if(e[u]!==null&&e[u]!==void 0){let a=_(e[u]);if(a==="symbol"||a==="function")throw new TypeError(`cannot serialize values of type '${a}'`);let d=Y.test(u)?u:L(u);if(a==="array"&&me(e[u]))o+=he(e[u],n?`${n}.${d}`:d,t-1,i);else if(a==="object"){let s=n?`${n}.${d}`:d;o+=`[${s}]
`,o+=R(e[u],s,t-1,i),o+=`

`}else l+=d,l+=" = ",l+=P(e[u],a,t,i),l+=`
`}}return`${l}
${o}`.trim()}function q(e,{maxDepth:n=1e3,numbersAsFloat:t=!1}={}){if(_(e)!=="object")throw new TypeError("stringify can only be called with an object");return R(e,"",n,t)}0&&(module.exports={TomlDate,TomlError,parse,stringify});
