var k=Object.defineProperty;var Y=Object.getOwnPropertyDescriptor;var q=Object.getOwnPropertyNames;var J=Object.prototype.hasOwnProperty;var R=e=>{throw TypeError(e)};var H=(e,n,i)=>n in e?k(e,n,{enumerable:!0,configurable:!0,writable:!0,value:i}):e[n]=i;var Q=(e,n)=>{for(var i in n)k(e,i,{get:n[i],enumerable:!0})},W=(e,n,i,t)=>{if(n&&typeof n=="object"||typeof n=="function")for(let l of q(n))!J.call(e,l)&&l!==i&&k(e,l,{get:()=>n[l],enumerable:!(t=Y(n,l))||t.enumerable});return e};var ee=e=>W(k({},"__esModule",{value:!0}),e);var D=(e,n,i)=>H(e,typeof n!="symbol"?n+"":n,i),Z=(e,n,i)=>n.has(e)||R("Cannot "+i);var m=(e,n,i)=>(Z(e,n,"read from private field"),i?i.call(e):n.get(e)),I=(e,n,i)=>n.has(e)?R("Cannot add the same private member more than once"):n instanceof WeakSet?n.add(e):n.set(e,i),g=(e,n,i,t)=>(Z(e,n,"write to private field"),t?t.call(e,i):n.set(e,i),i);var we={};Q(we,{TomlDate:()=>E,TomlError:()=>u,parse:()=>G,stringify:()=>X});module.exports=ee(we);function ne(e,n){let i=e.slice(0,n).split(/\r\n|\n|\r/g);return[i.length,i.pop().length+1]}function te(e,n,i){let t=e.split(/\r\n|\n|\r/g),l="",r=(Math.log10(n+1)|0)+1;for(let o=n-1;o<=n+1;o++){let a=t[o-1];a&&(l+=o.toString().padEnd(r," "),l+=":  ",l+=a,l+=`
`,o===n&&(l+=" ".repeat(r+i+2),l+=`^
`))}return l}var u=class extends Error{constructor(i,t){let[l,r]=ne(t.toml,t.ptr),o=te(t.toml,l,r);super(`Invalid TOML document: ${i}

${o}`,t);D(this,"line");D(this,"column");D(this,"codeblock");this.line=l,this.column=r,this.codeblock=o}};function b(e,n=0,i=e.length){let t=e.indexOf(`
`,n);return e[t-1]==="\r"&&t--,t<=i?t:-1}function O(e,n){for(let i=n;i<e.length;i++){let t=e[i];if(t===`
`)return i;if(t==="\r"&&e[i+1]===`
`)return i+1;if(t<" "&&t!=="	"||t==="\x7F")throw new u("control characters are not allowed in comments",{toml:e,ptr:n})}return e.length}function h(e,n,i,t){let l;for(;(l=e[n])===" "||l==="	"||!i&&(l===`
`||l==="\r"&&e[n+1]===`
`);)n++;return t||l!=="#"?n:h(e,O(e,n),i)}function C(e,n,i,t,l=!1){if(!t)return n=b(e,n),n<0?e.length:n;for(let r=n;r<e.length;r++){let o=e[r];if(o==="#")r=b(e,r);else{if(o===i)return r+1;if(o===t)return r;if(l&&(o===`
`||o==="\r"&&e[r+1]===`
`))return r}}throw new u("cannot find end of structure",{toml:e,ptr:n})}function $(e,n){let i=e[n],t=i===e[n+1]&&e[n+1]===e[n+2]?e.slice(n,n+3):i;n+=t.length-1;do n=e.indexOf(t,++n);while(n>-1&&i!=="'"&&e[n-1]==="\\"&&e[n-2]!=="\\");return n>-1&&(n+=t.length,t.length>1&&(e[n]===i&&n++,e[n]===i&&n++)),n}var ie=/^(\d{4}-\d{2}-\d{2})?[T ]?(?:(\d{2}):\d{2}:\d{2}(?:\.\d+)?)?(Z|[-+]\d{2}:\d{2})?$/i,x,y,w,p=class p extends Date{constructor(i){let t=!0,l=!0,r="Z";if(typeof i=="string"){let o=i.match(ie);o?(o[1]||(t=!1,i=`0000-01-01T${i}`),l=!!o[2],o[2]&&+o[2]>23?i="":(r=o[3]||null,i=i.toUpperCase(),!r&&l&&(i+="Z"))):i=""}super(i);I(this,x,!1);I(this,y,!1);I(this,w,null);isNaN(this.getTime())||(g(this,x,t),g(this,y,l),g(this,w,r))}isDateTime(){return m(this,x)&&m(this,y)}isLocal(){return!m(this,x)||!m(this,y)||!m(this,w)}isDate(){return m(this,x)&&!m(this,y)}isTime(){return m(this,y)&&!m(this,x)}isValid(){return m(this,x)||m(this,y)}toISOString(){let i=super.toISOString();if(this.isDate())return i.slice(0,10);if(this.isTime())return i.slice(11,23);if(m(this,w)===null)return i.slice(0,-1);if(m(this,w)==="Z")return i;let t=+m(this,w).slice(1,3)*60+ +m(this,w).slice(4,6);return t=m(this,w)[0]==="-"?t:-t,new Date(this.getTime()-t*6e4).toISOString().slice(0,-1)+m(this,w)}static wrapAsOffsetDateTime(i,t="Z"){let l=new p(i);return g(l,w,t),l}static wrapAsLocalDateTime(i){let t=new p(i);return g(t,w,null),t}static wrapAsLocalDate(i){let t=new p(i);return g(t,y,!1),g(t,w,null),t}static wrapAsLocalTime(i){let t=new p(i);return g(t,x,!1),g(t,w,null),t}};x=new WeakMap,y=new WeakMap,w=new WeakMap;var E=p;var le=/^((0x[0-9a-fA-F](_?[0-9a-fA-F])*)|(([+-]|0[ob])?\d(_?\d)*))$/,re=/^[+-]?\d(_?\d)*(\.\d(_?\d)*)?([eE][+-]?\d(_?\d)*)?$/,oe=/^[+-]?0[0-9_]/,fe=/^[0-9a-f]{4,8}$/i,j={b:"\b",t:"	",n:`
`,f:"\f",r:"\r",'"':'"',"\\":"\\"};function N(e,n=0,i=e.length){let t=e[n]==="'",l=e[n++]===e[n]&&e[n]===e[n+1];l&&(i-=2,e[n+=2]==="\r"&&n++,e[n]===`
`&&n++);let r=0,o,a="",f=n;for(;n<i-1;){let c=e[n++];if(c===`
`||c==="\r"&&e[n]===`
`){if(!l)throw new u("newlines are not allowed in strings",{toml:e,ptr:n-1})}else if(c<" "&&c!=="	"||c==="\x7F")throw new u("control characters are not allowed in strings",{toml:e,ptr:n-1});if(o){if(o=!1,c==="u"||c==="U"){let d=e.slice(n,n+=c==="u"?4:8);if(!fe.test(d))throw new u("invalid unicode escape",{toml:e,ptr:r});try{a+=String.fromCodePoint(parseInt(d,16))}catch(s){throw new u("invalid unicode escape",{toml:e,ptr:r})}}else if(l&&(c===`
`||c===" "||c==="	"||c==="\r")){if(n=h(e,n-1,!0),e[n]!==`
`&&e[n]!=="\r")throw new u("invalid escape: only line-ending whitespace may be escaped",{toml:e,ptr:r});n=h(e,n)}else if(c in j)a+=j[c];else throw new u("unrecognized escape sequence",{toml:e,ptr:r});f=n}else!t&&c==="\\"&&(r=n-1,o=!0,a+=e.slice(f,r))}return a+e.slice(f,i-1)}function z(e,n,i){if(e==="true")return!0;if(e==="false")return!1;if(e==="-inf")return-1/0;if(e==="inf"||e==="+inf")return 1/0;if(e==="nan"||e==="+nan"||e==="-nan")return NaN;if(e==="-0")return 0;let t;if((t=le.test(e))||re.test(e)){if(oe.test(e))throw new u("leading zeroes are not allowed",{toml:n,ptr:i});let r=+e.replace(/_/g,"");if(isNaN(r))throw new u("invalid number",{toml:n,ptr:i});if(t&&!Number.isSafeInteger(r))throw new u("integer value cannot be represented losslessly",{toml:n,ptr:i});return r}let l=new E(e);if(!l.isValid())throw new u("invalid value",{toml:n,ptr:i});return l}function ae(e,n,i,t){let l=e.slice(n,i),r=l.indexOf("#");r>-1&&(O(e,r),l=l.slice(0,r));let o=l.trimEnd();if(!t){let a=l.indexOf(`
`,o.length);if(a>-1)throw new u("newlines are not allowed in inline tables",{toml:e,ptr:n+a})}return[o,r]}function S(e,n,i,t){if(t===0)throw new u("document contains excessively nested structures. aborting.",{toml:e,ptr:n});let l=e[n];if(l==="["||l==="{"){let[a,f]=l==="["?M(e,n,t):K(e,n,t),c=C(e,f,",",i);if(i==="}"){let d=b(e,f,c);if(d>-1)throw new u("newlines are not allowed in inline tables",{toml:e,ptr:d})}return[a,c]}let r;if(l==='"'||l==="'"){r=$(e,n);let a=N(e,n,r);if(i){if(r=h(e,r,i!=="]"),e[r]&&e[r]!==","&&e[r]!==i&&e[r]!==`
`&&e[r]!=="\r")throw new u("unexpected character encountered",{toml:e,ptr:r});r+=+(e[r]===",")}return[a,r]}r=C(e,n,",",i);let o=ae(e,n,r-+(e[r-1]===","),i==="]");if(!o[0])throw new u("incomplete key-value declaration: no value specified",{toml:e,ptr:n});return i&&o[1]>-1&&(r=h(e,n+o[1]),r+=+(e[r]===",")),[z(o[0],e,n),r]}var ue=/^[a-zA-Z0-9-_]+[ \t]*$/;function V(e,n,i="="){let t=n-1,l=[],r=e.indexOf(i,n);if(r<0)throw new u("incomplete key-value: cannot find end of key",{toml:e,ptr:n});do{let o=e[n=++t];if(o!==" "&&o!=="	")if(o==='"'||o==="'"){if(o===e[n+1]&&o===e[n+2])throw new u("multiline strings are not allowed in keys",{toml:e,ptr:n});let a=$(e,n);if(a<0)throw new u("unfinished string encountered",{toml:e,ptr:n});t=e.indexOf(".",a);let f=e.slice(a,t<0||t>r?r:t),c=b(f);if(c>-1)throw new u("newlines are not allowed in keys",{toml:e,ptr:n+t+c});if(f.trimStart())throw new u("found extra tokens after the string part",{toml:e,ptr:a});if(r<a&&(r=e.indexOf(i,a),r<0))throw new u("incomplete key-value: cannot find end of key",{toml:e,ptr:n});l.push(N(e,n,a))}else{t=e.indexOf(".",n);let a=e.slice(n,t<0||t>r?r:t);if(!ue.test(a))throw new u("only letter, numbers, dashes and underscores are allowed in keys",{toml:e,ptr:n});l.push(a.trimEnd())}}while(t+1&&t<r);return[l,h(e,r+1,!0,!0)]}function K(e,n,i){let t={},l=new Set,r,o=0;for(n++;(r=e[n++])!=="}"&&r;){if(r===`
`)throw new u("newlines are not allowed in inline tables",{toml:e,ptr:n-1});if(r==="#")throw new u("inline tables cannot contain comments",{toml:e,ptr:n-1});if(r===",")throw new u("expected key-value, found comma",{toml:e,ptr:n-1});if(r!==" "&&r!=="	"){let a,f=t,c=!1,[d,s]=V(e,n-1);for(let _=0;_<d.length;_++){if(_&&(f=c?f[a]:f[a]={}),a=d[_],(c=Object.hasOwn(f,a))&&(typeof f[a]!="object"||l.has(f[a])))throw new u("trying to redefine an already defined value",{toml:e,ptr:n});!c&&a==="__proto__"&&Object.defineProperty(f,a,{enumerable:!0,configurable:!0,writable:!0})}if(c)throw new u("trying to redefine an already defined value",{toml:e,ptr:n});let[T,B]=S(e,s,"}",i-1);l.add(T),f[a]=T,n=B,o=e[n-1]===","?n-1:0}}if(o)throw new u("trailing commas are not allowed in inline tables",{toml:e,ptr:o});if(!r)throw new u("unfinished table encountered",{toml:e,ptr:n});return[t,n]}function M(e,n,i){let t=[],l;for(n++;(l=e[n++])!=="]"&&l;){if(l===",")throw new u("expected value, found comma",{toml:e,ptr:n-1});if(l==="#")n=O(e,n);else if(l!==" "&&l!=="	"&&l!==`
`&&l!=="\r"){let r=S(e,n-1,"]",i-1);t.push(r[0]),n=r[1]}}if(!l)throw new u("unfinished array encountered",{toml:e,ptr:n});return[t,n]}function F(e,n,i,t){var c,d;let l=n,r=i,o,a=!1,f;for(let s=0;s<e.length;s++){if(s){if(l=a?l[o]:l[o]={},r=(f=r[o]).c,t===0&&(f.t===1||f.t===2))return null;if(f.t===2){let T=l.length-1;l=l[T],r=r[T].c}}if(o=e[s],(a=Object.hasOwn(l,o))&&((c=r[o])==null?void 0:c.t)===0&&((d=r[o])!=null&&d.d))return null;a||(o==="__proto__"&&(Object.defineProperty(l,o,{enumerable:!0,configurable:!0,writable:!0}),Object.defineProperty(r,o,{enumerable:!0,configurable:!0,writable:!0})),r[o]={t:s<e.length-1&&t===2?3:t,d:!1,i:0,c:{}})}if(f=r[o],f.t!==t&&!(t===1&&f.t===3)||(t===2&&(f.d||(f.d=!0,l[o]=[]),l[o].push(l={}),f.c[f.i++]=f={t:1,d:!1,i:0,c:{}}),f.d))return null;if(f.d=!0,t===1)l=a?l[o]:l[o]={};else if(t===0&&a)return null;return[o,l,f.c]}function G(e,n){var a;let i=(a=n==null?void 0:n.maxDepth)!=null?a:1e3,t={},l={},r=t,o=l;for(let f=h(e,0);f<e.length;){if(e[f]==="["){let c=e[++f]==="[",d=V(e,f+=+c,"]");if(c){if(e[d[1]-1]!=="]")throw new u("expected end of table declaration",{toml:e,ptr:d[1]-1});d[1]++}let s=F(d[0],t,l,c?2:1);if(!s)throw new u("trying to redefine an already defined table or value",{toml:e,ptr:f});o=s[2],r=s[1],f=d[1]}else{let c=V(e,f),d=F(c[0],r,o,0);if(!d)throw new u("trying to redefine an already defined table or value",{toml:e,ptr:f});let s=S(e,c[1],void 0,i);d[1][d[0]]=s[0],f=s[1]}if(f=h(e,f,!0),e[f]&&e[f]!==`
`&&e[f]!=="\r")throw new u("each key-value declaration must be followed by an end-of-line",{toml:e,ptr:f});f=h(e,f)}return t}var U=/^[a-z0-9-_]+$/i;function A(e){let n=typeof e;if(n==="object"){if(Array.isArray(e))return"array";if(e instanceof Date)return"date"}return n}function ce(e){for(let n=0;n<e.length;n++)if(A(e[n])!=="object")return!1;return e.length!=0}function L(e){return JSON.stringify(e).replace(/\x7f/g,"\\u007f")}function P(e,n,i){if(i===0)throw new Error("Could not stringify the object: maximum object depth exceeded");if(n==="number")return isNaN(e)?"nan":e===1/0?"inf":e===-1/0?"-inf":e.toString();if(n==="bigint"||n==="boolean")return e.toString();if(n==="string")return L(e);if(n==="date"){if(isNaN(e.getTime()))throw new TypeError("cannot serialize invalid date");return e.toISOString()}if(n==="object")return de(e,i);if(n==="array")return me(e,i)}function de(e,n){let i=Object.keys(e);if(i.length===0)return"{}";let t="{ ";for(let l=0;l<i.length;l++){let r=i[l];l&&(t+=", "),t+=U.test(r)?r:L(r),t+=" = ",t+=P(e[r],A(e[r]),n-1)}return t+" }"}function me(e,n){if(e.length===0)return"[]";let i="[ ";for(let t=0;t<e.length;t++){if(t&&(i+=", "),e[t]===null||e[t]===void 0)throw new TypeError("arrays cannot contain null or undefined values");i+=P(e[t],A(e[t]),n-1)}return i+" ]"}function se(e,n,i){if(i===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let t="";for(let l=0;l<e.length;l++)t+=`[[${n}]]
`,t+=v(e[l],n,i),t+=`

`;return t}function v(e,n,i){if(i===0)throw new Error("Could not stringify the object: maximum object depth exceeded");let t="",l="",r=Object.keys(e);for(let o=0;o<r.length;o++){let a=r[o];if(e[a]!==null&&e[a]!==void 0){let f=A(e[a]);if(f==="symbol"||f==="function")throw new TypeError(`cannot serialize values of type '${f}'`);let c=U.test(a)?a:L(a);if(f==="array"&&ce(e[a]))l+=se(e[a],n?`${n}.${c}`:c,i-1);else if(f==="object"){let d=n?`${n}.${c}`:c;l+=`[${d}]
`,l+=v(e[a],d,i-1),l+=`

`}else t+=c,t+=" = ",t+=P(e[a],f,i),t+=`
`}}return`${t}
${l}`.trim()}function X(e,n){var t;if(A(e)!=="object")throw new TypeError("stringify can only be called with an object");let i=(t=n==null?void 0:n.maxDepth)!=null?t:1e3;return v(e,"",i)}0&&(module.exports={TomlDate,TomlError,parse,stringify});
